### ISSUE TITLE
rust-analyzer and library-ification

### ISSUE THREAD

**Issue by matklad** [rust-lang/compiler-team#160]
# Meeting proposal info

- **Title:** rustc-ide
- **Type:** technical
- **Proposed by:** @matklad 
- **Link:** https://gist.github.com/matklad/2d5f89a394cc70da97e5282fd6d88ef2
- **Scheduled dates for discussion:** [Sep 13, 2019](https://calendar.google.com/event?action=TEMPLATE&tmeid=MW00dnFnNzBycG9qbTNzYnNqYTZtZnRpaGogNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/proposals/_template.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
We discussed this in the [planning meeting today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/planning.20meeting.202019.2E08.2E30/near/174548296) and decided to schedule the topic for **Sep 13, 2019**.
