### ISSUE TITLE
Next steps for ICE breaker  group

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team#174]
- [x] we need a guide that helps people to get started with this sort of bug -- see https://github.com/rust-lang/rustc-guide/pull/452
- [x] we need some mechanism to make a github team people can subscribe to (as discussed here) -- @spastorino 
- [x] we need an announcement (maybe for the new team blog I am setting up!) -- [draft blog post in this hackmd doc](https://hackmd.io/_9rb_0rwTJWqQok2y59I9A)
- [x] sample PR for adding yourself https://github.com/rust-lang/team/pull/140
- [x] we need a github label -- done, ICEBreaker-LLVM
- [ ] we need to update our compiler-team page to drive attention to these groups as a way to contribute
- [ ] and maybe think about the main contribution page?
- [x] create a triagebot.toml file in rust-lang/rust ([sample](https://github.com/rust-lang/triagebot/issues/169#issuecomment-541358220)) https://github.com/rust-lang/rust/pull/65508/
- [x] we need a script people can copy/paste or -- better -- we need some command we can issue the triagebot. This fits with the discussion around "self-subscribing teams". https://github.com/rust-lang/rustc-guide/pull/463 -- @spastorino 
- [ ] compiler twitter account that tweets these things out

That bot would assign the label and write something like:

```
Hey LLVM icebreakers! This bug has been identified as a good
"LLVM ice-breaking candidate". In case it's useful, here are some
[general instructions] for tackling these sorts of bugs. Maybe take a look?

cc @foo @bar @baz ...
```

**Comment by nikomatsakis** [comment]
### Updates from meeting on 2019.09.26

* to track membership, we will create a `team/icebreakers-llvm.toml` file with minimal everything (not on website, no github team, etc)
    * but we have to be sure members do not get added to `all@`, have to check with @pietroalbini on the best way to do that

**Comment by spastorino** [comment]
This https://github.com/rust-lang/team/pull/123 is pending ...

**Comment by nikomatsakis** [comment]
Closing as done!
