### ISSUE TITLE
WG-traits does not list WG leaders

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#185]
WG-traits does not list WG leaders.

See https://rust-lang.github.io/compiler-team/working-groups/traits/#traits-working-group

It probably deviates from the standard template in other ways too.

**Comment by spastorino** [comment]
@nikomatsakis are there leaders defined in traits wg? if so let me know who they are and I can provide a PR.

**Comment by lqd** [comment]
yeah jack and niko are [listed as the leaders](https://github.com/nikomatsakis/team/blob/f289878c39216ba4539168f7526ea41b58f592c7/teams/wg-traits.toml#L6)
