### ISSUE TITLE
A unified framework for dataflow analysis

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/compiler-team#202]
# Meeting proposal info

After rust-lang/rust#64566, which was a prerequisite for [dataflow-based const validation](https://github.com/rust-lang/rust/pull/64470), there are [two](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/dataflow/generic.rs) different [frameworks](https://github.com/rust-lang/rust/blob/53aca553ec08e62a0591806fcf0f706ee9f53778/src/librustc_mir/dataflow/mod.rs#L671) for dataflow analysis in the compiler. I've written a [prototype](https://github.com/rust-lang/rust/compare/master...ecstatic-morse:unified-dataflow-proto) along with a [design document](https://hackmd.io/@39Qr_z9cQhasi25sGjmFnA/Skvd9rztS) for unifying the two frameworks.

The dataflow framework is an internal API (with the exception of one use in `cargo-clippy`), so this is a good time to improve it if desired. Accordingly, I've made some changes in the prototype, like passing `Statement`s and `Terminator`s directly into the `effect` methods, and making the signature of `call_return_effect` more similar to the others. If anyone has had difficulties implementing or inspecting the results of a dataflow analysis, it would be awesome to get your feedback here.

- **Title:** A unified framework for dataflow analysis
- **Type:** technical
- **Proposed by:** @ecstatic-morse
- **Link:** https://hackmd.io/@39Qr_z9cQhasi25sGjmFnA/Skvd9rztS
- **Scheduled dates for discussion:**
  - Not yet scheduled, we'll add content here when it gets scheduled

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/content/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/content/proposals/_index.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
We discussed this in our [planning meeting today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/planning.20meeting.202019.2E10.2E25) and decided to schedule it for discussion on **Nov 1, 2019**.

[Calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NWVxanM5MnVudW81ZmtrbDE5c2owb2IwY2IgNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com)

**Comment by mark-i-m** [comment]
Match in `const fn` here we come!

**Comment by nikomatsakis** [comment]
**Update:** Since @oli-obk will be unavailable, we've moved the date to **Nov 8**

**Comment by ecstatic-morse** [comment]
To clarify, this isn't blocking `if` and `match` in `const fn`. The necessary dataflow analysis was merged in rust-lang/rust#64566, and it has been used to check const bodies since rust-lang/rust#64470. It's just that this framework is completely separate from the existing `BitDenotation`, they don't share a `ResultsCursor` implementation, a graphviz visualization, etc. 

This design meeting is about merging the two frameworks into a single, shared one. Since this will require modifications whereever either framework is used, it is a good time to make changes to the existing API to make it [easier to comprehend](https://github.com/rust-lang/rust/pull/64566#pullrequestreview-289729516). It's also a good time to consider possible optimizations and extensions to this framework (extended basic blocks, customizable dataflow lattices, etc.) and make sure that the unified framework does not make any of these infeasible.

**Comment by nikomatsakis** [comment]
We had the meeting and added [minutes here](https://rust-lang.github.io/compiler-team/minutes/design-meeting/2019-11-09-unified-dataflow-framework), closing.
