### ISSUE TITLE
make a "Cleanup Crew" ICE-breakers for bisection 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#207]
Check list of things to do:

* [x] Create a Github label `ICEBreaker-Cleanup-Crew` [done](https://github.com/rust-lang/rust/labels/ICEBreaker-Cleanup-Crew)
* [x] Write a guide advising people on how to bisect-and-reduce and giving some high-level guidelines: https://github.com/rust-lang/rustc-guide/pull/556/
* [x] Configure the rust-lang/rust repository to support the ICE-breakers commands, similar to [this](https://github.com/rust-lang/rust/blob/c404ce689f7692f2c9b1df51803faf88ba11d2e8/triagebot.toml#L12-L21)
* [x] Create the cleanup crew toml file in team repo https://github.com/rust-lang/team/pull/214
* [x] Create a sample PR for adding yourself, similar to rust-lang/team#140
* [x] Link to the sample PR in [this section of the rustc-guide](https://rust-lang.github.io/rustc-guide/ice-breaker/about.html#joining-an-ice-breaker-group)
* [x] Write an announcement blog post

**Comment by spastorino** [comment]
I was taking a look at some stuff today on cargo-bisect-rustc, I guess waiting or not depends on what's the minimum stuff you want to see on the tool.

**Comment by spastorino** [comment]
>  Configure the rust-lang/rust repository to support the ICE-breakers commands, similar to this
Done: https://github.com/rust-lang/rust/pull/68581

>  Create a sample PR for adding yourself, similar to rust-lang/team#140
Done: https://github.com/rust-lang/team/pull/221

>  Link to the sample PR in this section of the rustc-guide
Done: https://github.com/rust-lang/rustc-guide/pull/565
