### ISSUE TITLE
Creating a OSS Fuzz project for Rust Compiler and stdlib

### ISSUE THREAD

**Issue by SiavoshZarrasvand** [rust-lang/compiler-team#212]
# Meeting proposal info

- **Title:** Creating a OSS Fuzz project for Rust Compiler and stdlib
- **Type:** Technical, but it's complicated, depends involvement. The gist explains it well.
- **Proposed by:** https://github.com/SiavoshZarrasvand/
- **Link:** https://gist.github.com/SiavoshZarrasvand/309028bc3fe42ee6af46be84a930e93d
- **Scheduled dates for discussion:**
  - Not yet scheduled, we'll add content here when it gets scheduled

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/content/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/content/proposals/_index.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
In [today's planning meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/planning.20meeting.202019.2E11.2E22/near/181640294), we discussed this issue. We decided we probably don't need a synchronous meeting on this -- there is general consensus that we should move forward with this. @SiavoshZarrasvand, @pnkfelix indicated an interest in following up with you and helping to find a good direction, maybe talk to them?
