### ISSUE TITLE
develop and mail out rustc licensing guidelines

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#220]
# Meeting proposal info

- **Title:** rustc licensing guidelines
- **Type:** non-technical
- **CC:** @skade 

# Summary

@skade has prepared a draft set of rustc licensing guidelines, available as a [dropbox paper document](https://paper.dropbox.com/doc/rustc-licensing-guidelines--Ao~xMyRsp7cmHLrQtvQPS_eQAg-13Vo9fltFmrsNrFpddiMA). These are meant to give practical advice for how to be respectful of licenses and also how to reach out for help if needed. I thought we could review the guidelines, offer suggestions and make sure we understand them, and decide where we want to post them.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/content/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/content/proposals/_index.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
Sees like this issue is at least semi-related: https://github.com/rust-lang/rust/issues/63232

**Comment by skade** [comment]
@pnkfelix it is indeed coming out of a number of issues where we had practical and theoretical licensing problems.

**Comment by pnkfelix** [comment]
For ease of future reference (transcribed from https://github.com/rust-lang/rust/issues/63232#issuecomment-517918295):

> Collecting a few Rust licensing infidelities:
>
> - https://github.com/rust-lang-nursery/compiler-builtins/issues/307
> - https://github.com/rust-lang-nursery/libm/issues/215
> - https://github.com/rust-lang/backtrace-rs/issues/234
> - https://github.com/sfackler/rust-openssl/issues/1147
> - https://github.com/rust-lang/rust/issues/63238

**Comment by nikomatsakis** [comment]
In today's design meeting, we decided to remove the "meeting proposal" from this issue and instead consider it as a "wg-meta work item"

**Comment by nikomatsakis** [comment]
We felt like a good idea would be to distribute guidelines via e-mail and perhaps do a meeting to talk them over.

**Comment by wesleywiser** [comment]
We updated the rustc-dev-guide with licensing considerations taken from the paper doc to help reviewers know what kinds of changes are acceptable from a licensing perspective. I don't think we need a dedicated steering meeting to review this (and this meeting proposal has been open for years now) so we're going close this as completed.
