### ISSUE TITLE
parser library-ification

### ISSUE THREAD

**Issue by matklad** [rust-lang/compiler-team#237]
# Meeting proposal info

- **Title:** parser library-ification
- **Type:** technical
  
# Summary

Parser and AST are fundamental components of the compiler, on top of each literally everything is build. We can't begin merging rustc and rust-analyzer without sharing them.

The goal of the meeting is twofold:
* share general experience with IDE-flavored parsing/trees in rust-analzyer (writeup: https://hackmd.io/XoQrzR8GRLa64jpjylQ7Bw) 
* get feedback on a semi concrete plan for the first steps of parser library-ification: https://hackmd.io/ifjST_Y4R-SQ0AWiEcU6FQ
* form consensus on what the next steps should be (and if we need this work in the first place)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/content/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/content/proposals/_index.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
We discussed this in our compiler-team planning meeting today. We've decided to schedule it for either Jan 24 or Feb 7. We're not sure yet which day is better as it depends on the availability of @petrochenkov and @estebank. ❤️

**Comment by nikomatsakis** [comment]
We have decided to schedule this meeting for **February 7th**.

**Comment by nikomatsakis** [comment]
I don't think anyone ever made minutes from this meeting, and I don't think it's worth doing it at this point. The [Zulip archive can be found here](https://zulip-archive.rust-lang.org/131828tcompiler/98989designmeeting20200207.html).
