### ISSUE TITLE
Cranelift backend for rustc

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/compiler-team#257]
# Meeting proposal info

- **Title:** Cranelift backend for rustc
- **Type:** technical
  
# Summary

The current LLVM backend for rustc is very good at optimizing functions. However it is not the fastest, even with optimizations disabled. When compiling in release mode this is not a big problem, but during development this can be annoying. [Cranelift](https://github.com/bytecodealliance/wasmtime/tree/master/cranelift) has the potential to improve compilation time, as it is optimized for compilation time as opposed to being optimized for good optimizations like LLVM. Over the course of the past ~1.5 year I have been working on a Cranelift based codegen backend for rustc ([rustc_codegen_cranelift](https://github.com/bjorn3/rustc_codegen_cranelift) or cg_clif for short). It is currently complete enough to compile many programs. While there are cases where LLVM is faster, Cranelift is already faster than LLVM in [many cases](https://github.com/bjorn3/rustc_codegen_cranelift/issues/878#issuecomment-597871730).

Rustc_codegen_cranelift is currently at a point where it may make sense to talk about bringing support in tree. This meeting proposal is about talking if we do want this and to talk about the future of rustc_codegen_cranelift in general.

[More details and meeting outline in this hackmd](https://hackmd.io/@bjorn3/HJL5ryFS8)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/content/proposals/_index.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by bjorn3** [comment]
More information can be found at https://hackmd.io/@bjorn3/HJL5ryFS8.

**Comment by RalfJung** [comment]
> The target feature detection x86 doesn’t work as inline assembly support is missing.

This is also [a problem for Miri](https://github.com/rust-lang/miri/issues/932). Would be great to find a unified solution. :)

**Comment by bjorn3** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/planning.20meeting.202020-03-13/near/190509615

> * April 3rd, 10am Boston time (usual time) -- cranelift
