### ISSUE TITLE
Rename Learning WG to rustc-dev-guide WG

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team#265]
This is the tracking issue of the rename of the Learning WG into rustc-dev-guide WG as it was discussed on this [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning/topic/rename.20working.20group).

Here is the list of things we should do in order to do the rename:

- [x] Rename our Github team from @rust-lang/wg-learning to @rust-lang/wg-rustc-dev-guide
- [x] Rename our Zulip #t-compiler/wg-learning stream into #t-compiler/wg-rustc-dev-guide and update the stream description accordingly
- [x] Rename our Zulip user group from @WG-learning into @WG-rustc-dev-guide
- [x] Rename the calendar events
- [x] Update this repository
  - [x] git mv content/working-groups/learning content/working-groups/rustc-dev-guide
  - [x] Update the files inside that directory to talk about rustc-dev-guide WG instead of Learning WG
  - [x] Update [main README](https://rust-lang.github.io/compiler-team/) to talk about rustc-dev-guide WG instead of Learning WG
  - [x] Rename learning to rustc-dev-guide in layouts/shortcodes/checkin-schedule.html
- [x] Rename [our listing in rust-lang/team](https://github.com/rust-lang/team/blob/master/teams/wg-learning.toml) to wg-rustc-dev-guide.toml and update the information accordingly.
- [x] Fix links on Github [repos](https://github.com/search?q=https%3A%2F%2Frust-lang.zulipchat.com%2F%23narrow%2Fstream%2F196385-t-compiler.2Fwg-learning&type=Code)
- [x] Fix links on Github [issues](https://github.com/search?q=https%3A%2F%2Frust-lang.zulipchat.com%2F%23narrow%2Fstream%2F196385-t-compiler.2Fwg-learning&type=Issues)
- [x] Announce on IRLO

**Comment by JohnTitor** [comment]
I think "Fix links on Github repos" is done. The last item is "Announce on IRLO", @spastorino do you have time to do? If not, I'm happy to do instead :)

**Comment by spastorino** [comment]
@JohnTitor have ticket the links on Github box, about the announcement on IRLO please go ahead :).

**Comment by JohnTitor** [comment]
Okay, posted: https://internals.rust-lang.org/t/learning-wg-is-now-rustc-dev-guide-wg/12192

**Comment by spastorino** [comment]
Closing this issue then :).
