### ISSUE TITLE
Code Generation Unit Partitioning Meeting

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/compiler-team#281]
# Meeting proposal info

- **Title:** Code Generation Unit Partitioning Meeting
- **Type:** Technical 
  
# Summary

The MIR Opt working group is making progress with various MIR optimizations.
However, our efforts are sometimes thwarted by compilation time regressions due to LLVM.
We believe the primary contributing factor in these situations is the codegen unit partitioning algorithm.

We would like to solicit ideas from the rest of the compiler team regarding improvements that can be made to the algorithm.

[Additional information can be found in this gist.](https://gist.github.com/wesleywiser/9a7e3ca53a948dabbf30b3a0b8635860)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
Scheduled for [May 22](https://calendar.google.com/event?action=TEMPLATE&tmeid=NzliMHQ4cTZnMW5oZ25qcjhtcmxqcTB0dW0gNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com)

**Comment by wesleywiser** [comment]
Assigning so that I remember to write meeting notes.

**Comment by pnkfelix** [comment]
At this point we are going to let the archive of the zulip stream serve as the record for the meeting: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bdesign.20meeting.5D.20codegen.20unit.20partitioning.20compiler-team.23281/near/198443239
