### ISSUE TITLE
make an ICE-breaker group for windows/aarch64

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#282]
Check list of things to do:

* [x] Create a Github label `ICEBreaker-Windows` -- or maybe use `O-windows`
* [x] Write a guide giving some high-level guidelines like https://github.com/rust-lang/rustc-dev-guide/pull/739, https://github.com/rust-lang/rustc-dev-guide/pull/740 -- PRs merged
* [x] Configure the rust-lang/rust repository to support the ICE-breakers commands, similar to [this](https://github.com/rust-lang/rust/blob/c404ce689f7692f2c9b1df51803faf88ba11d2e8/triagebot.toml#L12-L21) -- https://github.com/rust-lang/rust/pull/72706/ -- r+'d
* [x] Create the Windows/ARM toml file in team repo https://github.com/rust-lang/team/pull/347 -- merged!
* [x] Create a sample PR for adding yourself, similar to rust-lang/team#140 -- https://github.com/rust-lang/team/pull/348/ -- done, also for ARM with https://github.com/rust-lang/team/pull/358/
* [x] Write an announcement blog post 
* [ ] Remove "ICE-breaker" terminology from cleanup-crew, LLVM
* [ ] Remove the ICEBreaker-LLVM label and tag all issues that had it with A-LLVM
* [ ] Update links from older blog posts about LLVM, cleanup-crew, maybe add an EDIT about the new terminology

**Comment by nikomatsakis** [comment]
Drafting blog post here: https://hackmd.io/3oMWDAyGT8-GxV5p9nLRnw

**Comment by nikomatsakis** [comment]
Branch with rustc-dev-guide additions https://github.com/nikomatsakis/rustc-guide/tree/notification-groups

**Comment by spastorino** [comment]
- https://github.com/rust-lang/team/pull/347
- https://github.com/rust-lang/team/pull/348 (would need a rebase after #347 is in)
- https://github.com/rust-lang/pull/72706

**Comment by eddyp** [comment]
@nikomatsakis  ARM and aarch64 are two different things. I agree ARM-land nomenclature is confusing, but `ARM` is "all things ARM, be it no_std/std Cortex M/R/A", while `aarch64` is only about the `aarch64` is just the optional 64 bit architecture implemented on ARMv8 Cortex A cores.

Is there an ARM team, or is there an aarch64 team?

Sorry for the question, but for a person familiar with ARM-land, this confusion is making it difficult to decide if this info or the mechanism proposed in #282 is of interest.

**Comment by nikomatsakis** [comment]
I wound up creating just an ARM team, since we're trying to create "broader" groups in an effort to keep the total number of these sorts of groups under control. Plus, folks who know a lot about aarch64 likely know a lot about ARM too, I imagine. =) Anyway, this is done for now, so closing.

**Comment by eddyp** [comment]
@nikomatsakis there are still 3 unchecked boxes in the list above. Did you want to close #358 instead?

**Comment by nikomatsakis** [comment]
Ah, thanks for pointing that out. I forgot that I had added some check-boxes for an unrelated task (renaming of ICE-breaker groups...)

**Comment by nikomatsakis** [comment]
Created https://github.com/rust-lang/compiler-team/issues/309 for those
