### ISSUE TITLE
Roadmap 2020-2021

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#287]
# Meeting proposal info

- **Title:** Roadmap 2020-2021
- **Type:** non-technical
 
# Summary

The idea is to talk about the overall roadmap for the compiler team over the next year and a half or so. Before the meeting, I will be iterating on a hackmd that tries to lay out the kinds of use cases and goals we want to work towards, and names a few big initiatives.

This isn't meant to be an "exhaustive list" of all we will do -- in fact, it should leave room for unexpected twists. But it should highlight a few major initiatives.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

Here is a hackmd for this meeting: https://hackmd.io/3ES5_GhwTzOVmPS8AuaVvw

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
Schedule for [May 29](https://calendar.google.com/event?action=TEMPLATE&tmeid=NXA3bjl2aTRpN3NyZ2dtN21jbzRpMXNrMW4gNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com)

**Comment by pnkfelix** [comment]
To add to agenda at start:

- "error: expected identifier when building time-macros-impl v0.1.1" [#72545](https://github.com/rust-lang/rust/issues/72545)
  - It is also a regression.
  - Detected on day one.
  - Affects at least time, wasm-bindgen and syn.
  - It was also reported as https://github.com/rust-lang/rust/issues/72608

**Comment by nikomatsakis** [comment]
Assigning self to save notes/minutes
