### ISSUE TITLE
Areas of the compiler Meeting

### ISSUE THREAD

**Issue by spastorino** [rust-lang/compiler-team#288]
# Meeting proposal info

- **Title:** Areas of the compiler Meeting
- **Type:** non-technical
  
# Summary

The idea is to clearly define the areas of the compiler and its leads so we can organize our structure a bit better. 

This would be useful so we can define zulip streams for each area, we can have github teams so we can ping maintainers when there's a bug, each area would have recognized experts and owners,  and a zulip stream for them. These would also replace existing working groups that don't have specific goals.

We would also probably want to define this in `rust-lang/team`, replace experts.toml and we may be able to notify using some heuristics interested actors on issues. For instance, once a MIR label is added the members of the MIR area are contacted or something like that. 

[Additional information can be found in this HackMD document](https://hackmd.io/jdF3GQCkQRaR7VsmkigFag?view)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
At this point the public zulip archive will serve as the record for this meeting: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bdesign.20meeting.5D.20areas.20of.20the.20compiler.20compiler-team.23288/near/202093446
