### ISSUE TITLE
survey overview and discussion

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#290]
# Meeting proposal info

- **Title:** survey overview and discussion
- **Type:** non-technical

# Summary

@pnkfelix and I recently did a survey of the compiler team members and contributors. We've not tried to really "process" the results yet, but it might be useful to have a meeting to talk over the conclusions. (Though perhaps it's better to publish our analysis on Inside Rust first, so we can see if there are things that *need* to be discussed.)

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
An initial attempt to summarize the survey results: https://hackmd.io/gv41a48mRb-KV4SoJ0nXCA?edit

**Comment by nikomatsakis** [comment]
Scheduled for [May 15](https://calendar.google.com/event?action=TEMPLATE&tmeid=MGRuYmw4NGxwMDgwY2hib3IzbmoycjExcDQgNnU1cnJ0Y2U2bHJ0djA3cGZpM2RhbWdqdXNAZw&tmsrc=6u5rrtce6lrtv07pfi3damgjus%40group.calendar.google.com)

**Comment by pnkfelix** [comment]
At this point the public zulip archive will serve as the record for this meeting: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202020-05-15.20compiler-team.23290/near/197695110
