### ISSUE TITLE
Compiler Team Survey Results Meeting (part 2)

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/compiler-team#302]
# Meeting proposal info

- **Title:** Compiler Team Survey Results Meeting (part 2)
- **Type:** non-technical
  
# Summary

Finish the discussion started about the results of the compiler team survey.

The three high-level issues `@pnkfelix` identified that we ran out of time to discuss in the first meeting:

1. Long standing problems going unaddressed (or hard to track progress thereof; lack of status updates)

2. Worker drain and lack of bandwidth.

3. Change-to-test cycle is too long (more broadly, everything is too high latency)

## Specific notes from the survey results

1. Long standing problems going unaddressed (or hard to track progress thereof; lack of status updates)

    - Making it clear (or easier to identify) when an issue is blocked on a well-known pre-existing problem, e.g. lazy-normalization

    - Lack of regular retrospectives

    - Lots of projects but many are moving very slowly. Creates impression that nothing is happening.

2. Worker drain and lack of bandwidth

    - Contributor and paid-employee drain is worrisome

    - Lack of leadership bandwidth

    - Lack of mentoring bandwidth

    - Not sure we have workforce to accomplish all things that lang team designs. Recent acquistion of T-libs impl may add to this problem.

    - Risk of burnout.

3. Change-to-test cycle is too long (more broadly, everything is too high latency)

    - Lack of review bandwidth (both high review latency and low number of (active?) reviewers)

   - Debugging rustc is hard/doesn’t work, e.g. under rust-gdb

   - rustc's change-to-test cycle is too long
      - impedes contributing small patches

   - PR queue issues:
      - slow (low throughput)
      - “cannot” do full run of tests on all platforms

https://hackmd.io/gv41a48mRb-KV4SoJ0nXCA?view

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
At this point the public zulip archive will serve as the record for this discussion: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bdesign.20meeting.5D.20survey.20results.20part.202.20compiler-team.23302/near/201393165
