### ISSUE TITLE
`#[deny(unsafe_op_in_unsafe_fn)]` in liballoc

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/compiler-team#306]
# Proposal

Deny the newly-added `unsafe_op_in_unsafe_fn` lint in `liballoc`, which means that unsafe operations inside unsafe functions require an explicit unsafe block.

## Motivation

This is an opportunity for the language team to see the impact of the lint and decide of its future. It is also useful in the context of liballoc, where there are a lot of unsafe functions containing both safe and unsafe operations.

## Drawbacks

If the lint is removed, these additional unsafe blocks should be removed. However, this can probably be done automatically using e.g. `cargo fix`.

## Links

- Tracking Issue for "unsafe blocks in unsafe fn": rust-lang/rust#71668
- Proposed "implementation" PR: rust-lang/rust#72709

# Mentors or Reviewers

@Mark-Simulacrum is willing to second this. @RalfJung may also review as well?

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
@bors second

I'd like us to see more this feature "weathers" in libstd, and the downsides of this seem quite minimal.

**Comment by nikomatsakis** [comment]
@rustbot second

ETOOMANYBOTS

**Comment by LeSeulArtichaut** [comment]
So IIUC, MCPs need to be manually marked as accepted and closed? cc @nikomatsakis @spastorino

**Comment by nikomatsakis** [comment]
FCP expired, marking as accepted. Thanks @LeSeulArtichaut !
