### ISSUE TITLE
Meeting topic: Clean up labels on closed MCPs

### ISSUE THREAD

**Issue by richkadel** [rust-lang/compiler-team#307]
**Title:** Clean up labels on closed MCPs

**Estimate:** 1 meeting
**Type:** non-technical

# Summary

Recommend a person or bot update closed MCPs according to their final disposition.

# Motivation

It's hard to tell what MCPs are accepted or not.

# Details

I was reviewing the [list of closed MCPs](https://github.com/rust-lang/compiler-team/issues?q=is%3Aissue+is%3Aclosed+label%3Amajor-change) and it looks like several are closed that may be accepted, but don't have the major-change-accepted label. Many of the closed MCPs also say they are still in the "final-comment-period".

1. If there isn't already a rustbot activity for this, consider updating the rules to add `major-change-accepted`, remove `final-comment-period`, and close the issue, once a major change is accepted?
2. Someone (or some script) should update all of the closed MCPs with their correct disposition. (I'm not sure that all of them are accepted however.)

# Challenges

Just suggesting this for community awareness, but I don't have permissions to do this myself.

**Comment by spastorino** [comment]
Some days ago, I've gone over all the closed issues and added `major-change-accepted` to the ones accepted. You're right that we should also remove the `final-comment-period`, and I've just done so. @rust-lang/wg-prioritization is also starting to go over this list after our meetings that happen on thursday so I think we should be covered. Although, I think implementing some of this stuff using bots is a good idea.

**Comment by nikomatsakis** [comment]
I don't know that we really need a *meeting* about this topic, but I agree I forgot that we had a major-changed-accepted label for a period. =)

**Comment by spastorino** [comment]
I've fished all the labels some days ago. Before/after our meetings I plan to go over the labels to correct the ones from last week.

**Comment by nikomatsakis** [comment]
OK, I'm going to close this issue I think.
