### ISSUE TITLE
Move Rust provided objects, libraries and binaries meant for self-contained linkage to separate directory

### ISSUE THREAD

**Issue by mati865** [rust-lang/compiler-team#310]
# Proposal

This affects only three targets: `windows-gnu`, `linux-musl`, `-wasi`.
Currently startup objects (all three targets) and libraries (`windows-gnu`) and placed next to Rust's own libraries like libstd.
This causes various problems, e.g. somebody wants to link external libraries with Rust but CRT shipped by Rust is incompatible with the one used to link external library.
For `windows-gnu` there is also linker shipped.

https://github.com/rust-lang/rust/issues/68887#issuecomment-633048380 explains how to resolve that limitation by creating native and self-contained modes. Native mode would avoid using anything located inside `self-contained` directory.

https://github.com/rust-lang/rust/pull/72999 is preparation that moves things but retains old user visible behaviour (everything is linked just like before, only the paths are different).

# Mentors or Reviewers

@petrochenkov 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
@mati865 you're meant to replace this text:

> *Insert your proposal here, overwriting this text. Please include the complete proposal, rather than linking to a gist or other external document.* 

with the actual proposal...I at least don't really know what your proposal is based only on the title alone. :)

**Comment by mati865** [comment]
@nikomatsakis I've accidentality hit enter while typing the title and it opened the issue... 😬
Updated the text.

**Comment by mati865** [comment]
Seems like zulip thread doesn't exist?

**Comment by mati865** [comment]
Are the docs up-to-date and FCP should last 10 days?
