### ISSUE TITLE
RISC-V Linux Tier 2 Host support

### ISSUE THREAD

**Issue by tblah** [rust-lang/compiler-team#312]
# Proposal

Support `riscv64gc-unknown-linux-gnu` hosts at Tier 2. The Tier 2 support currently [advertised](https://forge.rust-lang.org/release/platform-support.html) on rust-forge is [only for cross compilation](https://github.com/rust-lang/rust/pull/72973#issuecomment-640460271).

- [PR adding a builder](https://github.com/rust-lang/rust/pull/72973)
- [Infrastructure team approval](https://github.com/rust-lang/rust/pull/72973#issuecomment-645434400)
- [PR adding a testing image](https://github.com/rust-lang/rust/pull/73171)
- [PR adding RISC-V notification group](https://github.com/rust-lang/team/pull/362)

# Mentors or Reviewers

@nikomatsakis 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
OK, I'm not sure the best way to make approvals for Tier 2, but I propose that we go with FCP for now. To that end, I would like to propose to @rust-lang/compiler that we elevate RISC-V Linux to Tier 2 support. This would mean that we would check that it continues to build and that we can build it not only in cross-compiling mode but also on a RISC-V system, self-hosted.

The @rust-lang/infra team already [gave their assent](https://github.com/rust-lang/rust/pull/72973#issuecomment-645434400) here. We have a [proposed notification group](https://github.com/rust-lang/team/pull/362) of folks that would help with maintenance. 

Moving to Tier 2 is certainly not irreversible, but it will mean that we distribute binaries with rustup, so withdrawing support would be quite noticeable. The main risk I see is that if we start getting more RISC-V specific bug reports, it will be hard for us to reproduce: but we're not committed to support at this tier, and the notification group should help with resolving such issues.

@rfcbot fcp merge
