### ISSUE TITLE
`#![deny(unsafe_op_in_unsafe_fn)]` in libcore and libstd

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/compiler-team#317]
# Proposal

In the continuity of #306 (accepted few days ago), this MCP proposes to deny the `unsafe_op_in_unsafe_fn` in `libcore` and `libstd`, which means that unsafe operations inside unsafe functions require an explicit unsafe block.

## Motivation

This is an opportunity for the language team to see the impact of the lint and decide of its future.

## Drawbacks

If the lint is removed, these additional unsafe blocks should be removed. However, this can probably be done automatically using e.g. `cargo fix`.

## Links

- Tracking Issue for "unsafe blocks in unsafe fn": rust-lang/rust#71668
- Proposed "implementation" PR for `libcore`: rust-lang/rust#73622
- Tracking issue for `libstd`: rust-lang/rust#73904

# Mentors or Reviewers

@nikomatsakis, who seconded #306 and is in favor of this change, will probably second this MCP.
@RalfJung and @Mark-Simulacrum may also review the changes.

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
@rustbot second

I'm not sure this needed a second MCP, but in any case I approve.

**Comment by LeSeulArtichaut** [comment]
Should this be marked as accepted now? Also rust-lang/rust#73622 was merged 🎉

**Comment by nikomatsakis** [comment]
Yep, MCP accepted.
