### ISSUE TITLE
Portable SIMD project group

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/compiler-team#321]
# Proposal

Create a project group for considering what portable SIMD in the standard library should look like.

As a practical matter, I think the multi-ISA-tested running code in the `packed_simd` crate should be used as the starting point. Compiler back ends in general and LLVM in particular already have a dominant design for the general shape of portable SIMD. It makes sense to expose that kind of general API shape in the standard library in order to avoid exposing lower-level compiler intrinsics. The `packed_simd` crate already has multi-ISA-tested running code for an API shape that is a good fit for what compiler back ends in general and LLVM in particular expose in this domain. Other kinds of designs can be layered over this by the crate ecosystem.

Notably, `packed_simd` is already a restart from scratch compared to the `simd` crate. While the internals differ, the general API shape ended up being similar despite initially trying to simplify things away. (Notably, `packed_simd` initially tried to not have boolean/mask vectors that `simd` had but LLVM doesn't have but ended up re-introducing them.) It's not a good use of anyone's time to start from scratch again.

See an [FAQ](https://github.com/hsivonen/rfcs/blob/ppv/text/0000-ppv.md#faq) for more.

# Mentors or Reviewers

@joshtriplett [advised](https://rust-lang.zulipchat.com/#narrow/stream/196563-t-lang.2Fwg-meta/topic/Promoting.20packed_simd.20to.20std.3A.3Asimd/near/201776949) me to file an MCP about this.

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/lang-team/issues/29
