### ISSUE TITLE
Use `tracing` instead of `log`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#331]
# Proposal

1. Replace all uses of the `log` crate with `tracing` (there are verbatim replacements for the logging macros, so no code changes)
2. Replace all uses of `{:?}` in tracing macro invocations with `?value` infront of the format string
3. Introduce `span!` invocations to give us hirerarchical logs

# Mentors or Reviewers

* @oli-obk 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by eddyb** [comment]
@rustbot second

cc @hawkw @davidbarsky @jackh726

**Comment by hawkw** [comment]
:wave: I'd be happy to help out with this, either in the form of answering questions and giving advice, or in the form of actually sending PRs. :)

Note that because `tracing` has an [adapter](https://docs.rs/tracing-log/0.1.1/tracing_log/#convert-log-records-to-tracing-events) for converting `log::Record`s into `tracing` `Event`s, it's also possible to do the migration incrementally, crate-by-crate.
