### ISSUE TITLE
Stabilizable subset of const generics

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/compiler-team#332]
# Proposal

We should create a new feature `min_const_generics`, which contains a subset of the const generics feature suitable for stabilization.

This will impose two restrictions on const generics:

1. They can only have the type of an integral primitive type (integers, bool, and char).
2. Expressions used in const generic position must be either:
    - Just a const generic name in scope (e.g. `N`)
    - A const expression which contains on no free type or const parameters.

The latter will be implemented simply syntactically: if an expression contains a type or const parameter in its macro-expanded AST, it will error, unless it is just the name of a const generic.

This feature will not depend on lazy normalization of consts.

# Mentors or Reviewers

@eddyb @varkor @oli-obk

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by oli-obk** [comment]
Kicking off the FCP. I personally see no difficulties here

@rfcbot fcp merge

**Comment by eddyb** [comment]
We're not doing seconding for this?

**Comment by nikomatsakis** [comment]
For public facing changes, FCP is required, but for stabilizations it's usually attached to the PR. It seems like the first step here is going to be carving out a distinct feature gate for this subset and then stabilizing *that*, and I don't think that necessarily requires FCP. Nonetheless, I approve of the idea.

**Comment by spastorino** [comment]
Prioritization automation failed because the bot didn't add the `proposed-final-comment-period` label. I've fixed `T-compiler` agenda manually. Maybe `@rfcbot` doesn't have permission to label issue in this repo?.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Added rfcbot with write permissions to this repo.

**Comment by petrochenkov** [comment]
I'm ok with this if wg-const-eval and eddyb are sure that the implementation is no longer at prototype stage, and the stabilized subset won't have issues that can't be fixed backward compatibly (due to lazy normalization, scoping of generic parameter environment, or what other problems we had).

**Comment by nikomatsakis** [comment]
We recently had a lang-team meeting on this with those folks present. We'll definitely be digging into that before we fully stabilize things.
