### ISSUE TITLE
Create a WebAssembly target notification group.

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/compiler-team#337]
# Proposal

Create a WebAssembly (wasm) target notification group which can be pinged whenever a wasm-specific issue might come up in the compiler. Additionally this target group can assist in triaging bugs if notified. The label for this group would be `O-wasm`

# Mentors or Reviewers

N/A (?)

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by LeSeulArtichaut** [comment]
I think this proposal should be accepted now? cc @spastorino
