### ISSUE TITLE
Set ninja=true by default

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/compiler-team#339]
# Proposal

Ninja substantially improves LLVM build time. On a 96-way system, using
Make took 248s, and using Ninja took 161s, a 35% improvement.

We already require a variety of tools to build Rust. If someone wants to
build without Ninja (for instance, to minimize the set of packages
required to bootstrap a new target), they can easily set ninja=false
in config.toml. Our defaults should help people build Rust (and LLVM)
faster, to speed up development.

I've implemented this change to the defaults in
https://github.com/rust-lang/rust/pull/74922

# Mentors or Reviewers

cc @nikomatsakis @oli-obk @Mark-Simulacrum 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by tmandry** [comment]
As a data point, this is how we build rust for fuchsia. I don't think it's ever caused any problems.

**Comment by LeSeulArtichaut** [comment]
@spastorino This one also should be accepted?
