### ISSUE TITLE
Stabilise `link-self-contained` option

### ISSUE THREAD

**Issue by mati865** [rust-lang/compiler-team#343]
# Proposal

Continuation of https://github.com/rust-lang/compiler-team/issues/310

Short summary on how this option works on supported targets (`windows-gnu`, `linux-musl`, `wasi`):
* no value: rustc will use heuristic to disable self-contained mode if system has necessary tools.
* `y`, `yes`, `on`: use only libraries/objects shipped with Rust.
* `n`, `no`, or `off`: rely on the user or external linker to provide non-Rust libraries/objects.

# Mentors or Reviewers

@petrochenkov made the design here: https://github.com/rust-lang/rust/issues/68887#issuecomment-633048380

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by petrochenkov** [comment]
@rustbot second
Feels a bit like seconding myself, but anyway.
