### ISSUE TITLE
Add StatementKind::Intrinsic to MIR

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/compiler-team#348]
# Proposal

Extend Mir to include statements for specific intrinsic function calls that are known to not panic or unwind under any conditions. Currently, function calls can only be used in terminator position, but permitting intrinsics which have better known behaviour to be interspersed will make it easier to create optimizations in the future.

Create a specialized terminator for the optimization of certain intrinsics. Specifically, proposing `StatementKind::CopyNonOverlapping` since memcpy is a function we often want to optimize over. The structure of the statement for this intrinsic would be `StatementKind::CopyNonOverlapping { src: Box<Place<'tcx>>, dst: Box<Place<'tcx>>, size: Operand }`. This would be easy enough to convert in the future to a nested `StatementKind::Intrinsic` operator if more additions are added. 

# Mentors or Reviewers

@oli-obk 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by eddyb** [comment]
> Extend Mir to include statements for specific intrinsic function calls that are known under any circumstance to panic or unwind.

Is this missing a negation?

**Comment by JulianKnodt** [comment]
ah yes, yes it is

**Comment by nagisa** [comment]
@rustbot third

I’m willing to review changes that implement this too, so do r? me on implementation PRs as well.

**Comment by RalfJung** [comment]
> Extend Mir to include statements for specific intrinsic function calls that are known to not panic or unwind under any conditions. 

Additionally, these intrinsics must also be known to always return (i.e., they must never cause an infinite loop).
