### ISSUE TITLE
Don't build tools by default with `x.py build`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/compiler-team#351]
# Proposal

After #326, the default filter for `x.py build` is essentially `x.py build library/std src/tools/*`. Since most contributors don't work on rustdoc or other tools, this might be unexpected, and will delay compile times if you're only working on the standard library. I propose to change the default filter to `x.py build library/std`.

For additional discussion, see https://github.com/rust-lang/blog.rust-lang.org/pull/666#discussion_r470162204, https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Improve.20defaults.20in.20x.2Epy.20compiler-team.23326/near/206924772. 

# Mentors or Reviewers

@RalfJung (and possibly @eddyb) for creating a consensus
@Mark-Simulacrum for the implementation

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by jyn514** [comment]
The implementation for this was closed, @spastorino can you remove `major-change-accepted`?

**Comment by spastorino** [comment]
You meant that this was accepted but then rejected and it's not going to be implemented? or why would you remove `major-change-accepted`?

**Comment by jyn514** [comment]
> You meant that this was accepted but then rejected and it's not going to be implemented?

Yes, that's what I mean. See https://github.com/rust-lang/rust/pull/77489 for more discussion.

As an aside, I'm not a giant fan of the MCP process for exactly things like this, objections happen afterwards and the 'approval' doesn't actually mean anything.
