### ISSUE TITLE
Accept RFC 2951 "Linking modifiers for native libraries"

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/compiler-team#356]
# Proposal

Accept [RFC 2951 "Linking modifiers for native libraries"](https://github.com/rust-lang/rfcs/pull/2951) that provides some generic syntax (similar to target features) for linking modifiers used for native libraries, and introduces some specific modifiers to control bundling behavior, whole-archive linking and library name mangling.

# Mentors or Reviewers

@petrochenkov 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by pnkfelix** [comment]
I just re-read the protocol and realized that this requires full team check off.

**Comment by pnkfelix** [comment]
@rfcbot rfc merge

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
Accepted!
