### ISSUE TITLE
`ty.kind()` -> `ty.data()`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#359]
# Proposal

* Rename `ty.kind()` and similar methods to `ty.data()` -- the `data` method, more generally, would be used to get from the interned thing to data that was interned
* Rename `TyKind` to `TyData`
* Same for other types

This matches the chalk naming scheme. There are two main advantages:

* the term `Kind` also has a meaning in type theory, where it refers to the "kinds" of generic arguments one can have (e.g., types, lifetimes, constants)
* the term `Kind` doesn't apply to all the things we would like to intern, such as slices of types and so forth

The eventual goal of extracting a shared type library is that we should be able to work generically with all interned types (to allow for alternative interning schemes), and in that case we need a generic term to access their "data".

# Mentors or Reviewers

@leseulartichaut is willing to do the impl work, and @nikomatsakis can review.

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by LeSeulArtichaut** [comment]
Note: there have been concerns raised on the associated Zulip topic, this should probably not be accepted yet.

**Comment by spastorino** [comment]
@nikomatsakis how should we proceed here? maybe remove `final-comment-period` and have somebody seconding this again when there are no more concerns?.

**Comment by nikomatsakis** [comment]
Given the concerns that were raised and recent discussion in the traits working group, I'm going to close this issue. We're considering two things now:

* first off, there's a bunch of other work we can pursue, and we can defer this particular change
* second, we may wish to have `data()` yield a `TyData` that is actually corresponding to `TyS`, and leave `TyKind` the same
