### ISSUE TITLE
Add 32-bit and 64-bit stderr/stdout files for ui tests

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#365]
# Proposal

Similarly to how mir-opt tests can generate an output file for each bit width, we would allow ui tests to do the same for its stderr/stdout dump files. This would be entirely opt-in, so all ui tests keep behaving as they do now, but if you add

```rust
// emit-stderr-for-each-bitwidth
```

to the test file, then you get a `.64bit.stderr` file instead of a plain `.stderr` file. When you run the test on 32 bit you get a `.32bit.stderr` file. Only the file for your platform is tested, so you need to rerun the test with `--target i686-unknown-linux-gnu` on a 64 bit host in order to check the 32 bit test file.

The reason I am suggesting this is that it's nearly impossible to specify a useful normalization regex for https://github.com/rust-lang/rust/pull/76881 . The point is to test the output, ideally for each platform individually.

# Mentors or Reviewers

* @oli-obk 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by hameerabbasi** [comment]
Copying over the [concern on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/Looking.20for.20help.20on.20.2353325/near/210657121) for visibility: It'd be hard to generate `*.32bit.stderr` files on macOS 10.15+ due to [32-bit binaries being forbidden](https://support.apple.com/en-us/HT208436).

**Comment by hameerabbasi** [comment]
I have an implementation of this over at rust-lang/rust#81817, waiting for the MCP approval.

**Comment by oli-obk** [comment]
This has been implemented in https://github.com/rust-lang/rust/pull/81817 now
