### ISSUE TITLE
Internal lint: Ban `pub` re-exports in compiler/

### ISSUE THREAD

**Issue by jyn514** [rust-lang/compiler-team#368]
# Proposal

This is an MCP for rust-lang/rust#65233 (Internal lint: Ban `pub` re-exports)

## Why make this change?

- re-exports obscure which crate an item is defined in
- re-exports add non-canonical paths: should I import `rustc_hir::def_id::LOCAL_CRATE` or `rustc_span::def_id::LOCAL_CRATE`?
- re-exports can add unnecessary dependencies to the crate graph, slowing down compile times (due to lack of parallelism) and making refactors more difficult

### What is the long-term goal?

The long-term goal is to split up rustc_middle as per https://github.com/rust-lang/rust/issues/65031. I'm thinking of doing that by moving out `rustc_middle::ty` to `rustc_ty`, but I'm not set on that; accepting this MCP should not count as accepting the `rustc_middle` change.

## Why not make this change?

- Churn
- You now have to care where items are defined when you didn't before.

## Proposed approach

- Deny public re-exports by default.
- Allow public re-exports in the following crates/modules:
  + `rustc_data_structures` (as per https://github.com/rust-lang/rust/pull/77479#issuecomment-703061714)
  + `librustc_mir::interpret` (as per https://github.com/rust-lang/rust/issues/65233#issuecomment-541320264)
  + Other crates can be allowed as decided by the compiler team. However, to the extent possible, I would prefer to _not_ allow this in most crates at time of implementation, so that there's a clear distinction between 'crates intentionally not following the lint' and 'crates which have not yet been transitioned to using the lint' (by simply not having any crates in the second category).

There is a half-finished implementation of this in https://github.com/rust-lang/rust/pull/77479.

# Mentors or Reviewers

I am not sure who should mentor. Perhaps @lcnr is interested?

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by lcnr** [comment]
Can mentor but not a member of t-compiler, so I don't think I can second this.

**Comment by lcnr** [comment]
>  compiler team member or contributor who is knowledgeable in the area can second by writing `@rustbot second`.

didn't realize contributors can also second :sweat_smile: 

@rustbot second

**Comment by petrochenkov** [comment]
Looks like this is currently in FCP to accept, but one PR applying a subset of this proposal was recently closed - https://github.com/rust-lang/rust/pull/77494.
So it seems like his suggestion should rather be done on case by case basis, than as a general policy.

**Comment by jyn514** [comment]
Sounds good to me.
