### ISSUE TITLE
inherit stable annotations in enum variants and field items

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#370]
# Proposal

Some time back, @estebank opened https://github.com/rust-lang/rust/pull/71481 which proposed to fix https://github.com/rust-lang/rust/issues/65515 by allowing stability attributes to be 'inherited'. The idea is that if you declare a struct/enum to be stable, then you are also declaring (by default) all of its public fields to be stable. 

The primary motivation for the change is diagnostics. In our error messages, we sometimes print type declarations by excerpting from the source, and those currently contain various stability attributes that distract the user.

This change also reduces the annotation burden. As @estebank argues in #65515, it is quite unusual to have a stable struct/enum with public fields that are unstable (although I've not tried to verify this by inspection). In #65515, @alexcrichton [commented](https://github.com/rust-lang/rust/issues/65515#issuecomment-548457772):

>  I think we've never had a case for public enums and private variants [..] so removing all the internal attributes should be fine.

@dtolnay [commented](https://github.com/rust-lang/rust/issues/65515), and @SimonSapin [concurred](https://github.com/rust-lang/rust/issues/65515#issuecomment-548782720):

> Removing #[stable] from public enum variants and their fields both seem good to me. This isn't something we would need right away but what would make sense to me is if public elements of an item (its variants and fields) inherit #[stable] from the item, with explicit #[unstable] to negate that behavior.

The main downside is that if we DO have a struct that is stabilized, but we do not wish to stabilize its public fields, we have to remember to explicitly annotate those fields as UNSTABLE, as @nagisa [pointed out](https://github.com/rust-lang/rust/pull/71481#discussion_r436266259).

Based on the above comments I believe the change makes sense, both for error messages and to reduce annotation burden. 

# Mentors or Reviewers

@estebank has already prepared the PR

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [x] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by pnkfelix** [comment]
Discussed at T-compiler meeting; we're going to put this through a full FCP process rather than the MCP seconding process.

@rfcbot fcp merge

**Comment by nagisa** [comment]
@rfcbot reviewed

I still think libstd is in a position where additional care regarding stability of its APIs warrants the annotation burden, but I don't have much reason to block this.

**Comment by nikomatsakis** [comment]
Closing as accepted. The PR is rust-lang/rust#71481
