### ISSUE TITLE
[mir-opt] I accidentally pushed to the master branch

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#39]
I thought I had setup my own fork already. The relevant commit is https://github.com/rust-lang/compiler-team/commit/65896859e29bd111d7877997350aabc581e97cdc

You can comment on the commit directly and I'll open a PR with the requested changes.

@rust-lang/infra can we have bors + a locked master branch here, too?

**Comment by davidtwco** [comment]
The [NOTES.md file](https://github.com/rust-lang/compiler-team/commit/65896859e29bd111d7877997350aabc581e97cdc#diff-dd49e92e22cf685bea0ec487e7cc6aac) needs updated. That's also an excellent commit message.

**Comment by wesleywiser** [comment]
I [left a comment](https://github.com/rust-lang/compiler-team/commit/65896859e29bd111d7877997350aabc581e97cdc#r32706038) on the `NOTES.md` file.

**Comment by pietroalbini** [comment]
Bors is not useful for this repo since it doesn't have any kind of CI. Protected branches to prevent force pushes can be setup though.
