### ISSUE TITLE
Staged queries

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/compiler-team#391]
# Proposal

The current query system caches query results for the entire lifetime of the `TyCtxt`.
However, some of these results may not be useful after certain stages.
For instance, the HIR could be dropped once the MIR is built.
If the parser is ever querified, the AST will have to be dropped once the HIR is built.

We propose to split the query system into *stages*.
Each stage starts from an intermediate representation of the compiler, and produces another one.
For example:
- Nothing to AST,
- AST to HIR,
- HIR to MIR,
- MIR to LLVM bitcode.

Inside each stage, only a subset of queries are accessible, and we retain the pull-based compilation scheme.
The `TyCtxt` will be split into `ParseCtxt`, `LoweringCtxt`, `TyCtxt`, `MirCtxt`.
The dependency graph remains global, and deals with the different stages.

For each stage, a set of *output* queries are `ensure`d manually.
(This should be done so that no unnecessary information is loaded from the incremental on-disk cache.)
The cache for those output queries is moved as the cache for *input* queries for the next stage.
We drop the rest of the caches.

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by bjorn3** [comment]
No zulip topic was created.

**Comment by apiraino** [comment]
[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Staged.20queries.20compiler-team.23391)
