### ISSUE TITLE
Embed version numbers in backport nominations and regression labels

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#393]
# Proposal

The rust-lang/rust github repo should replace the labels `beta-nominated`, `beta-accepted`, `regression-from-stable-to-beta`, and `regression-from-stable-to-nightly` with new labels that have version numbers embedded in them: for example `v1.49-nominated` or `regression-from-stable-to-v1.51`. (The labels `regression-from-stable-to-stable`, `stable-nominated`, and `stable-accepted` would remain unchanged; once a problem is in stable, its not really something where its too useful to track the version any more (apart from knowing if its become ancient)

Every release (thus every six weeks), we would "retire" the labels whose versions just became the stable version (where "retire" means stop using or perhaps outright delete), and create new labels for the version that has just started its journey on the train. (Also, every release, existing searches would need to be updated to reflect the version number changes; that, or we would need a bot to maintain the old-style labels so that the searches could remain as is.)

Advantages of a scheme with explicit version numbers: It is less confusing, especially around the time when the train is shifting beta->stable and nightly->beta, about what the labels are saying needs to be done. Also, the labels would remain "up to date" even after such a shift (as opposed to today, where e.g. a regression-stable-to-nightly label needs to be manually updated after the shift to say regression-stable-to-beta).

Disadvantages of a scheme with explicit version numbers: Creating and retiring the labels is additional work every six weeks. Updating the github searches is additional work. Tagging a ticket with the appropriate label may be harder than it is today (i.e. having more labels to choose between may be difficult; but if a bot does it in response to a comment, then presumably a bot can figure out the right label to add based on the current train state).

# Mentors or Reviewers

I saw @Mark-Simulacrum mention in Zulip that they have long wanted a system like this in place.

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by lqd** [comment]
Zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Embed.20version.20numbers.20in.20GH.20labels.20compiler-team.23393

**Comment by apiraino** [comment]
Closing MCP for inactivity (+3 months) (see [MCP process](https://forge.rust-lang.org/compiler/mcp.html#when-should-major-change-proposals-be-closed)). Feel free to re-open to further the discussion, though.
