### ISSUE TITLE
(recurring) regression day

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/compiler-team#401]
# Meeting proposal info

- **Title:** regression day
- **Type:** technical
  
# Summary

Spend time processing regressions and making sure they're assigned, roughly halfway through the cycle.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
Discussed with @Mark-Simulacrum at planning meeting. We've decided on a different direction; a targeted meeting with just the leads scheduled on an ad-hoc basis seems like it works better for this.

Closing.
