### ISSUE TITLE
Filter out query machinery from compiler backtraces by default

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#410]
# Proposal

The backtraces emitted by the compiler contain mostly irrelevant noise with the interesting parts sprinkled somewhere in between. I propose to filter out the irrelevant part with `RUST_BACKTRACE=1` and only emit them with `RUST_BACKTRACE=full`. My proposed implementation strategy would be to add attributes to the functions that we don't want to see in backtraces and have rustc automatically collect the symbol names of these functions and put them into a table that is stored in metadata. The `rustc_driver` crate will then create a magic `static SKIP_BACKTRACE_SYMBOLS: &[&str] = &[];` item that doesn't actually have a useful body, but will instead get filled in by the const evaluator. This allows the driver to feed that list to the backtrace reporting machinery.

# Mentors or Reviewers

* @pnkfelix 

# Process

The main points of the [Major Change Process][MCP] is as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by Mark-Simulacrum** [comment]
@rustbot second

I think this idea should work and seems positive, and we should largely be able to work out any possible problems during implementation.
