### ISSUE TITLE
Rename -Cllvm-args to something backend agnostic

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/compiler-team#421]
# Proposal

Rustc currently has a stabilised codegen flag named `llvm-args` for passing arguments to the LLVM backend, however the way this currently works it allows you to pass arguments to any codegen backend not just LLVM. For example, it is used in `cg_clif` and we are interested in using it in `rust-gpu`.

With rustc supporting more and more backends it would be nice if the arguments and flags users were using had less LLVM specific naming. Since the argument has already been stabilised there will need to be some sort of migration path for people on stable currently using it.

### Steps

1. Introduce new backend agnostic version of `-Cllvm-args`
    - Potential names (`-Cbackend-args`, `-Ccodegen-args`, `-Ccodegen-backend-args`)
2. From here there are two different roads for migration of the `-Cllvm-args` users.
    - Deprecate use of `-Cllvm-args` and recommend people use the new argument.
    - Continue to accept `-Cllvm-args` and provide an error when used with a different backend.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by nagisa** [comment]
@rfcbot second

**Comment by apiraino** [comment]
Closing now (MCP was not closed after the FCP expired)

**Comment by XAMPPRocky** [comment]
Should there be a tracking issue on rust-lang/rust now?

**Comment by jonas-schievink** [comment]
We don't tend to use tracking issues for MCPs, just an implementation is enough
