### ISSUE TITLE
Write text output files to stdout if options like `-o -` or `--emit asm=-` are provided

### ISSUE THREAD

**Issue by pjhades** [rust-lang/compiler-team#431]
# Proposal

Currently, rustc writes output to files, even if options like `-o -` or `--emit asm=-` are specified. But sometimes it would be convenient if rustc writes text output (`asm`, `dep-info`, `llvm-ir` and `mir`) to stdout if the user explicitly asks for it, so that the output could be easily read or piped to consumer programs. For example I could write a simple name demangler and pipe the assembly output to it to make a poor man's command-line [compiler explorer](https://godbolt.org/).

There are a few open issues where people proposed the same thing, like https://github.com/rust-lang/rust/issues/47112 and https://github.com/rust-lang/rust/issues/26719.

For gcc and clang, when `-o -` is provided, assembly output (produced via `-S`) will be written to stdout instead of a `<source_file_name>.s` file. Dependency information (produced via `-MD`) will still be written to a file called `-.d`. Preprocessor output (produced via `-E`) will always be written to stdout.

# Mentors or Reviewers

I'm not sure who to include here.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

[MCP]: https://forge.rust-lang.org/compiler/mcp.html
[forge]: https://forge.rust-lang.org/

**Comment by pnkfelix** [comment]
Actually this is public facing, so it needs full team checkoff.

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

**Comment by apiraino** [comment]
@rustbot label -final-comment-period +major-change-accepted

(closing only now because slipped through the cracks)
