### ISSUE TITLE
1.52 Fingerprint retrospective (aka COE)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#435]
# Meeting proposal info

- **Title:** 1.52 Fingerprint Retrospective
- **Type:** It's complicated

# Summary

The compiler team should have a retrospective on the 1.52.0 release issues with fingerprints that led to an emergency release of 1.52.1. @pnkfelix will take lead on preparing a document discussing 1. the events in our development and release process that led to the issues in the 1.52.0 release, 2. how we subsequently discovered the issues and responded to them in the short-term, and 3. what steps we can take going forward to reduce risk of re-occurrence of similar events in the future.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
We have so far had two meetings on this topic ([2021-06-25][jun-25-zulip-archive], [2021-07-02][jul-02-zulip-archive]), and a third meeting is scheduled for 2021-07-09.

 
[jun-25-zulip-archive]: https://zulip-archive.rust-lang.org/238009tcompilermeetings/56399steeringmeeting20210625152retrocompilerteam435.html

[jul-02-zulip-archive]: https://zulip-archive.rust-lang.org/238009tcompilermeetings/74498steeringmeeting20210702fingerprintsplanning.html

**Comment by wesleywiser** [comment]
Since we've had these meetings and the chat transcripts are linked above, I'm going to close this as completed.
