### ISSUE TITLE
Allow changing the bug report url for the ice hook

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/compiler-team#436]
# Proposal

The bug report url is currently hard-coded to https://github.com/rust-lang/rust/issues/new. This is a sensible location for rustc and other official users of rustc_driver, but in case of external tools there is a big chance that the ICE is actually caused by the tool and not rustc. For this reason it makes sense to allow changing the bug report url for the ice hook.

This is implemented in https://github.com/rust-lang/rust/pull/85640.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jonas-schievink** [comment]
Since you can already override the panic hook with your own, and print the URL there, this seems like a reasonable addition

@rustbot second
