### ISSUE TITLE
Transfer on-disk hash table implementation (odht crate) to rust-lang org

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/compiler-team#438]
# Proposal

I would like to transfer my ["on-disk" hash table implementation](https://github.com/michaelwoerister/odht) to the `rust-lang` GH organization. The crate is production-ready and is useful for encoding and decoding data in incr. comp. caches and crate metadata. The first use case for it is https://github.com/rust-lang/rust/pull/82183 where it allows simplifying the existing code while making it faster at the same time.

I don't expect this crate to require much maintenance - but it would certainly be good to give it a good review before the transfer. 

# Mentors or Reviewers

@wesleywiser has agreed to review this MCP.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rfcs/pull/3119

**Comment by wesleywiser** [comment]
@rustbot second

This seems like a good fit for the "Internal Use - Not transitively intentional" category of crates outlined in RFC 3119.
