### ISSUE TITLE
Accept `pc` in place of `unknown` and `unknown` in place of `pc` for `x86_64` and `i?86` targets

### ISSUE THREAD

**Issue by chorman0773** [rust-lang/compiler-team#441]
# Proposal

Currently in rustc, targets with the vendor `pc` vs. `unknown` are considered distinct. In particular, the target `x86_64-pc-linux-gnu` is not accepted by rustc as a target, whereas `x86_64-unknown-linux-gnu`. Likewise, `x86_64-pc-windows-msvc` is accepted but `x86_64-unknown-windows-msvc` is not. There is no functional difference between the targets, beyond the canonical (and actual) name, but this distinction can make using rustc (or cargo) with other tools that operate on target tuples annoying. 
For example, on my system (Ubuntu 21.04, GNU/Linux),  `config.guess` from GNU autotools reports my host system target as `x86_64-pc-linux-gnu`. As a further example, `config.sub` canonicalizes `x86_64-linux-gnu` as `x86_64-pc-linux-gnu`, not `x86_64-unknown-linux-gnu`. Both cases can be mitigated with [72 lines of shell script](https://github.com/chorman0773/rust-autotools/blob/ba30541e192e277cf5ccb8b4a3f7bf0a50c898bc/m4/lcrust_prog_rustc.m4#L32..L104), however it is annoying and is arguably a hack. 

The proposal is to have rustc treat the `pc` and `unknown` vendors as identical for x86_64 and i?86 (i586 and i686), and accept targets with either, reguardless of the system (os-env) components. The proposal can also include having rustc canonicalize targets, though that is not strictly necessary as use cases that need to pass targets to rustc can canonicalize using config.sub, <https://crates.io/crate/target-tuples>, or some other canonicalization mechanism. Some prior discussion on this proposal occured [on this IRLO thread](https://internals.rust-lang.org/t/expand-targets-acceptable-to-rustc/14885)

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by pnkfelix** [comment]
FYI: this will be closed in a week if it doesn't get seconded within that time.

See also: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-05-19/near/282934125
