### ISSUE TITLE
Non exhaustive reachable patterns lint

### ISSUE THREAD

**Issue by DevinR528** [rust-lang/compiler-team#445]
# Proposal

Add a new lint that checks for missing patterns in matches and destructuring assignment of `non_exhaustive` enums and structs. 
This was suggested in the original `non_exhaustive` PR https://github.com/rust-lang/rust/pull/45394 and there is an open issue https://github.com/rust-lang/rust/issues/84332 for this lint as well as a very early PR https://github.com/rust-lang/rust/pull/86809.

If the attribute is put on the wildcard pattern there is this issue with `..` https://github.com/rust-lang/rust/issues/81282.

Example

```rust
// crate x
#[non_exhaustive]
pub struct Foo {
    a: u8,
    b: usize,
    c: String,
}

#[non_exhaustive]
pub enum Bar {
    A,
    B,
    C,
}

// crate y
match Bar::A {
    Bar::A => {},
    Bar::B => {},
    #[deny(reachable)] // attribute goes here or on the expresion
    _ => {} // triggers lint "missing Bar::C..."
}

let Foo { 
    a
    b,
    #[warn(reachable)]
    .. // triggers lint "missing field `c`..."
} = structure;
```

# Mentors or Reviewers

@davidtwco who is a reviewer on the lint PR and implemented `non_exhaustive`.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by pnkfelix** [comment]
This landed in https://github.com/rust-lang/rust/pull/86809
