### ISSUE TITLE
`-Dwarnings` to cover all warnings

### ISSUE THREAD

**Issue by ojeda** [rust-lang/compiler-team#473]
# Proposal

Currently, `-Dwarnings` does not cover all warnings (e.g. `target json file contains unused fields` is not treated as an error). If it is intended that `-Dwarnings` covers all warnings, then this should be fixed (otherwise, it would be nice to have an alternative way to make them errors as needed). However, as @jyn514 pointed out, this would imply existing projects may require changes; thus a MCP was requested.

(Followup from https://github.com/rust-lang/rust/issues/91262).

# Mentors or Reviewers

Someone from "Diagnostics"?

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
MCP candidate for closing next week (reason: lack of seconding from a member of T-compiler). See [MCP process](https://forge.rust-lang.org/compiler/mcp.html#when-should-major-change-proposals-be-closed).

**Comment by ojeda** [comment]
For reference: https://github.com/rust-lang/rust/issues/91262#issuecomment-1151063209.
