### ISSUE TITLE
Introduce a new linter for diagnostic meesages

### ISSUE THREAD

**Issue by hkmatsumoto** [rust-lang/compiler-team#478]
# Proposal

Introduce a linting system, separated from clippy or internal lints, for diagnostic messages on ui tests.

## Motivation

Diagnostics play an important role in mitigating the steep learning curve of Rust. To make them easier to understand, their wording and use of punctuations should be consistent to some extent. Currently, it is the reviewer's job to spot inconsistency before being merged, but since reviewers are not omniscient and omnipotent, they sometimes overlook them (e.g., https://github.com/rust-lang/rust/pull/89482, https://github.com/rust-lang/rust/pull/89483).

# Mentors or Reviewers

PR is at https://github.com/rust-lang/rust/pull/89455

@estebank (assignee of the PR)

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by estebank** [comment]
I am slightly concerned about `diaglint` living outside of the main repo. We have a very high to adding new deps. That being said, I am very much on favor of the *idea*, if not the approach.

@rustbot second

with the understanding that we will have to iterate on the specific approach before it can be merged/enabled.
