### ISSUE TITLE
Discuss concrete ways of making incr. comp. more robust

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/compiler-team#490]
# Meeting proposal info

- **Title:** Discuss concrete ways of making incr. comp. more robust
- **Type:** it's complicated
  
# Summary

I don't have a concrete proposal of what to discuss -- but I've written a long document with possible topics:

https://hackmd.io/@michaelwoerister/SJf9VU1-5

Maybe we can make things more concrete in the planning meeting.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
This meeting will be taking place on 2022-04-01, on Zulip under the #t-compiler/meetings stream, here: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202022-04-01.20compiler-team.23490/near/277004037

**Comment by pnkfelix** [comment]
We met on 2022-04-01

We discussed this doc: https://hackmd.io/@michaelwoerister/SJRXZBVQ5

The previously linked zulip archive will serve as the meeting record: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202022-04-01.20compiler-team.23490/near/277004037
