### ISSUE TITLE
Implement `Clone` for generators

### ISSUE THREAD

**Issue by canndrew** [rust-lang/compiler-team#494]
# Proposal

It would be nice if generators, like closures, could automatically implement `Clone` and `Copy` where possible. Is this something that the lang team would consider desirable? (It would certainly be useful to me).

There is some prior discussion of this on zulip here: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60Clone.60.20for.20generators

# Mentors or Reviewers

@tmandry? @estebank?

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by canndrew** [comment]
I have implemented this here: https://github.com/canndrew/rust/tree/clone-generators

Would someone be willing to review it?

**Comment by nikomatsakis** [comment]
@rustbot label +I-lang-nominated

Let's discuss this briefly in the lang meeting, but it seems good to me. The idea is to make generators implement Clone/Copy if they can, just as closures do now.

**Comment by nikomatsakis** [comment]
We [discussed this in today's @rust-lang/lang meeting](https://github.com/rust-lang/lang-team/blob/master/minutes/2022-03-22.md#implement-clone-for-generators-compiler-team494) and the general consensus was that we were **in favor** of this change and that no RFC was required (this can be considered a logical extension of <https://github.com/rust-lang/rfcs/pull/2132>. It would still require a tracking issue and an FCP on the PR that implements it -- it would also be good, @canndrew, to do a write-up of the proposed design for that issue (presumably a small one) to help guide the stabilization report.

**Comment by canndrew** [comment]
Sorry for the delayed response. I've been busy with work/life.

I've updated the PR to pass the CI checks and I've opened [a tracking issue](https://github.com/rust-lang/rust/issues/95360) which includes a short write-up of the feature. Is this write-up the sort of thing you had in mind?
