### ISSUE TITLE
Removing codegen logic for `nvptx-nvidia-cuda` (32-bit target)

### ISSUE THREAD

**Issue by kjetilkjeka** [rust-lang/compiler-team#496]
# Proposal

The `nvptx-nvidia-cuda` (32-bit) target is no longer available in the Rust compiler, and 32-bit ptx is not well supported by Nvidia. The `nvptx64-nvidia-cuda` is the target used for generating 64-bit ptx which is fully supported by Nvidia.

Unfortunately the code for generating ptx function signatures contains a lot of bugs in the way args are passed to LLVM, this goes for both 32-bit and 64-bit ptx. [I have started fixing these bugs](https://github.com/rust-lang/rust/pull/94703) for the nvptx64 target but have not yet touched the nvptx target. My proposal is to remove the nvptx codegen module (`rustc_target::abi::call::nvptx`) entirely instead of fixing the bugs there as well.

Since the `nvptx-nvidia-cuda` target is removed from rustc it is not trivial to rely on the target. Since the code contains quite a lot of breaking bugs in function arguments codegeneration and 32-bit ptx is not well supported by Nvidia it reinforces the assumption that nobody is relying on this code.

# Mentors or Reviewers

Removing this code should be very simple and mentoring should not be needed. @RDambrosio016 will be consulted for looking through the PR as he his working on rust-cuda and is more knowledgeable about this topic than myself. I do not know who will be the most suitable reviewer for this change. @davidtwco is assigned to the bugfix PR and it might make sense to have the same person assigned to several nvptx related things.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by eddyb** [comment]
@rustbot second

(happened to see the list of MCPs and I 100% agree with the reasoning here - see also https://github.com/rust-lang/rust/issues/65111)
