### ISSUE TITLE
Promote `x86_64-unknown-none` to Tier 2

### ISSUE THREAD

**Issue by bstrie** [rust-lang/compiler-team#499]
# Proposal

Promote the `x86_64-unknown-none` target to [Tier 2](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2).

This target was originally proposed for Tier 3 in https://github.com/rust-lang/compiler-team/issues/462 and implemented in https://github.com/rust-lang/rust/pull/89062 .

## [Tier 2 Target Requirements](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-2-target-policy)

> A tier 2 target must have value to people other than its maintainers.

This target is useful to anyone doing bare-metal development on x86-64, including kernels and firmware.

> A tier 2 target must have a designated team of developers.

This target is maintained by @haraldh and @mikeleany .

> The target must not place undue burden on Rust developers not specifically concerned with that target.

Other than lacking an OS, this target is standard x86-64. This target deliberately does not support libstd, so it imposes no additional library burden.

> The target must provide documentation for the Rust community explaining how to build for the target using cross-compilation, and explaining how to run tests for the target.

Documentation is provided for [building](https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64-unknown-none.html#building-rust-programs) and [testing](https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64-unknown-none.html#testing).

> The target must document its baseline expectations for the features or versions of CPUs, operating systems, libraries, runtime environments, and similar.

Documentation is provided for [platform requirements](https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64-unknown-none.html#requirements).

> If introducing a new tier 2 or higher target that is identical to an existing Rust target except for the baseline expectations for the features or versions of CPUs, operating systems, libraries, runtime environments, and similar, then the proposed target must document to the satisfaction of the approving teams why the specific difference in baseline expectations provides sufficient value to justify a separate target.

There are two similar Tier 3 targets: `x86_64-unknown-none-hermitkernel` and `x86_64-unknown-none-linuxkernel`. The maintainers of the former are amenable to replacing their target with `x86_64-unknown-none`: https://github.com/rust-lang/rust/pull/90404. The maintainer of the latter also appears amenable to using a standardized target: https://github.com/rust-lang/rust/pull/64051#issuecomment-706764376 . We envision that `x86_64-unknown-none` will supplant these two targets.

> Tier 2 targets must not leave any significant portions of core or the standard library unimplemented or stubbed out, unless they cannot possibly be supported on the target. As an exception, a target identical to an existing tier 1 target except for lower baseline expectations for the OS, CPU, or similar, may propose to qualify as tier 2 (but not higher) without support for std if the target will primarily be used in no_std applications, to reduce the support burden for the standard library. In this case, evaluation of the proposed target's value will take this limitation into account.

This target qualifies for the listed exception. While libstd cannot be supported, there is no difficulty in supporting libcore.

> The code generation backend for the target should not have deficiencies that invalidate Rust safety properties, as evaluated by the Rust compiler team.

I hope the compiler team will confirm, but as far as I am aware there is no deficiency in LLVM's ability to generate stack probes etc. for this target.

> If the target supports C code, and the target has an interoperable calling convention for C code, the Rust target must support that C calling convention for the platform via extern "C".

This target supports `extern "C"` via the System V calling convention (without red zones).

> The target must build reliably in CI, for all components that Rust's CI considers mandatory.

We have not yet tried to build in CI, but I see no reason to suspect this will not be satisfied.

> The approving teams may additionally require that a subset of tests pass in CI.

None of the other `unknown-none` targets appear to run any tests as part of CI.

> Building the target in CI must not take substantially longer than the current slowest target in CI, and should not substantially raise the maintenance burden of the CI infrastructure.

This is not anticipated.

> Tier 2 targets should, if at all possible, support cross-compiling.

This target does not provide host tools, so it exclusively supports cross-compiling.

> In addition to the legal requirements for all targets (specified in the tier 3 requirements), because a tier 2 target typically involves the Rust project building and supplying various compiled binaries, incorporating the target and redistributing any resulting compiled binaries (e.g. built libraries, host tools if any) must not impose any onerous license requirements on any members of the Rust project, including infrastructure team members and those operating CI systems.

Distributing this target does not involve distributing any new third-party code.

> Tier 2 targets must not impose burden on the authors of pull requests, or other developers in the community, to ensure that tests pass for the target.

This target runs no tests.

> The target maintainers should regularly run the testsuite for the target, and should fix any test failures in a reasonably timely fashion.

Same as the previous.

# Mentors or Reviewers

@joshtriplett 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by joshtriplett** [comment]
> > Tier 2 targets must not leave any significant portions of core or the standard library unimplemented or stubbed out, unless they cannot possibly be supported on the target. As an exception, a target identical to an existing tier 1 target except for lower baseline expectations for the OS, CPU, or similar, may propose to qualify as tier 2 (but not higher) without support for std if the target will primarily be used in no_std applications, to reduce the support burden for the standard library. In this case, evaluation of the proposed target's value will take this limitation into account.
> 
> This target qualifies for the listed exception. While libstd cannot be supported, there is no difficulty in supporting libcore.

Clarifying here: the exception you're referring to is "unless they cannot possibly be supported on the target"? (Not having an OS is not "lower baseline expectations for the OS". :) )

(I agree that you're meeting this requirement.)

**Comment by bstrie** [comment]
@apiraino Now that the FCP is over and there have been no objections, can this be merged?
