### ISSUE TITLE
Add a weak warning lint level

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/compiler-team#509]
# Proposal

Add a weak warning lint level that does not highlight the source code or display its messages to the console.
If there were weak warnings, rustc prints `weak warning: X weak warnings were hidden`. The rationale is that people do not want the warnings to occupy the terminal (when compiling/running), but still have them displayed in editors.

To do this, `-Z weak_warn` should be added which would allow `#![weak_warn(LINTS_OR_LINT_GROUPS)]`. Specifying what lints should be suppressed to weak_warn level can also be done with `-Zweak_warn=LINTS_OR_LINT_GROUPS`.

The JSON output from cargo should also be changed such that weak warnings are distinguishible normal warnings. Those outputs would still include spans and messages, for IDEs and tools.

Rustfix should not fix weak warnings by default.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by nikomatsakis** [comment]
This feels to me like a language change (cc @rust-lang/lang) and I think merits a [lang team proposal](https://lang-team.rust-lang.org/initiatives/process/stages/proposal.html).

**Comment by fee1-dead** [comment]
I'm going to close this myself and reopen it once I have a clearer picture of what this feature should look like.
