### ISSUE TITLE
Link to rust-lang/cargo-lockfile-sync in content/procedures/crates.md is invalid

### ISSUE THREAD

**Issue by NiklasJonsson** [rust-lang/compiler-team#523]
The procedures/crates.md file links to https://github.com/rust-lang/cargo-lockfile-sync/ (at the very bottom) which results in a 404 for me. I don't mind fixing this but I'm not sure if it should be removed or replaced? I can't find anything similar by searching in rust-lang at least.

**Comment by wesleywiser** [comment]
@oli-obk it looks like you added the reference to that repo back in 2019 (ad42c66c52558a6dbf8322e5d39c1d8ae6c47109). Do you know what happened to `cargo-lockfile-sync`? 

I'm guessing it should probably just be removed.

**Comment by oli-obk** [comment]
I don't remember this

**Comment by bjorn3** [comment]
According to https://github.com/rust-lang/rust/issues/57443#issuecomment-966441719 it ended up in cargo-edit as `cargo upgrade --to-lockfile`.

**Comment by NiklasJonsson** [comment]
PR is #524
