### ISSUE TITLE
Add `#[alias]` attribute to allow symbol aliasing

### ISSUE THREAD

**Issue by carbotaniuman** [rust-lang/compiler-team#526]
# Proposal

ELF platforms along with Windows allow specifying aliases for symbols  (I am unsure about Mac). The semantics of aliases are that is simply another name to the same symbol, with no extra layers of indirection, and is available in C as a GCC extension:
`int __attribute__((weak, alias("__read"))) read();`.

The attribute is similar to the `#[linkage]` attribute, in that is not designed to be exposed stably, but portions of it may be stabilized depending on use-cases. The syntax would be as follows, applied to an existing function declaration or static, and accepted values for `linkage` would be `external` and `weak`.

The attribute can be repeated to allow for multiple aliases, but each `name` field must be globally unique to avoid duplicate symbol definitions.
```
#[alias(name = "read_from_a_thingie")] // should imply `linkage = "external"`
#[alias(name = "read", linkage = "weak")]
#[no_mangle]
extern "C" fn __read() {
...
}
```

The main use-case for this feature would be current work on Mustang, a libc implemented in Rust, which unfortunately requires a lot of platform-specific shenanigans. This would "properly" fix https://github.com/rust-lang/compiler-builtins/issues/70, although that appears to already have a working workaround.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
Closing MCP (reason: superseded by a `T-lang` initiative, as mentioned on the [Zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Add.20.60.23.5Balias.5D.60.20attribute.20to.20allow.20symbol.20.E2.80.A6.20compiler-team.23526)), see [MCP process](https://forge.rust-lang.org/compiler/mcp.html#when-should-major-change-proposals-be-closed) for closing MCPs.
