### ISSUE TITLE
Deref is not a projection

### ISSUE THREAD

**Issue by ouz-a** [rust-lang/compiler-team#532]
# Proposal

### Motivation
The MIR uses `Place` to refer to memory locations. A `Place` consists of a base, either a static or a local, and a series of projections starting from that base. With one exception, these projections are merely refinements of the base: they specify a field, an array element, or the portion of memory corresponding to a given enum variant. However, the `Deref` projection is unique in that the target of the  `Place` refers to a completely different region of memory than the base. As a result, several analyses must iterate over each place to see whether that place contains a `Deref`.

### Solution
Convert 

```rust
let x = (*a.b).c
```

into

```rust
let tmp = a.b;
let x = (*tmp).c
```

### Plan
- Create a new mir-opt(derefer) that does the above-mentioned conversion
- Pull `derefer`, earlier in the optimization phases
- Create new `Rvalue` for `derefer`
- *everything above has already been done*
- Pull `derefer` before borrowck
- Make it so MIR `Body` is built in a way that the transformation becomes unnecessary
- Remove `ProjectionElem::Deref` entirely. 
    - add a `deref: bool` field to `Place`, which indicates that the place must be dereferenced before its projections are applied.

Read more about [it here](https://hackmd.io/@gfCWRnJPTvCK5U9fN_vp7Q/By2jRlN35)

# Mentors or Reviewers
@oli-obk 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by safinaskar** [comment]
I hope this major change doesn't conflict with deref patterns ( https://github.com/rust-lang/lang-team/issues/77 )
