### ISSUE TITLE
Add `#[rustc_safe_intrinsic]` attribute

### ISSUE THREAD

**Issue by CohenArthur** [rust-lang/compiler-team#546]
# Proposal

Relevant PR https://github.com/rust-lang/rust/pull/100719

Some intrinsics of the core library are usable in safe context, despite being declared as `extern "rust-intrinsic"` functions. This concerns intrinsics such as `rotate_left`, which are indeed not "unsafe" functions in themselves. However, the list of these safe intrinsics is not directly apparent within the `core` library source code (the explanation is however present in the documentation). In order to mark an intrinsic as safe or unsafe, the compiler instead relies on a hardcoded list of symbols as shown [here](https://github.com/rust-lang/rust/blob/187654481fd828e495919295369d33827f10e1c4/compiler/rustc_typeck/src/check/intrinsic.rs#L64-L108).

Since the safety of these intrinsics is sometimes subject to changes, it is hard to keep up with the list of safe and unsafe intrinsics, which is why the addition of a source-level `#[rustc_safe_intrinsic]` attribute would lighten the mental load.

Such attributes already exist: For example, some intrinsics are usable in constant contexts. Because the intrinsics are declared as extern, the syntax also forbids the usage of the `const` keyword. Hence, `#[rustc_const_stable]` and `#[rustc_const_unstable]`, among other things, serve to mark these intrinsic functions as constant.

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

*This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.*

**Comment by wesleywiser** [comment]
@rustbot second 

I'm also happy to review patches if needed
