### ISSUE TITLE
Raise minimum supported macOS and iOS versions

### ISSUE THREAD

**Issue by BlackHoleFox** [rust-lang/compiler-team#556]
# Proposal

I propose to raise the minimum versions to macOS 10.12 (Sierra) and iOS 10 to better match recent expectations for developers publishing on these platforms and to clean up the compiler and standard library. Additionally, the minimum tvOS version would be raised to 10 as well to match iOS.

`rustc` and the standard library currently support back to macOS 10.7 (OSX Lion) and iOS 7. However, both of these versions have long since been marked deprecated and unsupported by Apple, not having received an update for 9 to 8 years, respectively. While that may not be extremely old for other platforms such as Linux, the Apple ecosystem is known for most of its userbase staying on modern versions. Both macOS 10.12, iOS 10, and tvOS 10 use [the same](https://en.wikipedia.org/wiki/MacOS_Sierra#Release_history) [kernel](https://www.theiphonewiki.com/wiki/Kernel#iOS.2FiPadOS), Darwin v16. By increasing each's minimum version at the same time, problem cases where APIs are available only on one OS can be avoided, which prevents unnessecarily cluttering the stdlib.

## macOS specific

Looking at what versions other programming languages support:

| Language             | Supported version            |
|----------------------|------------------------------|
| Go[^1]               | 10.13+                       |
| Zig (unofficial)[^2] | 10.12+                       |
| Swift[^3]            | 10.9+ (with bundled runtime) |
| Java[^4]             | 10.15+                       |
| Python 3[^5]         | 10.9+                        |
| Julia[^6]            | 10.9+                        |

[^1]: https://go.dev/dl/
[^2]: https://github.com/ziglang/zig/pull/9545
[^3]: https://www.swift.org/platform-support/
[^4:]: https://www.oracle.com/java/technologies/javase/products-doc-jdk18certconfig.html
[^5]: https://www.python.org/downloads/release/python-3106/
[^6]: https://julialang.org/downloads/platform/#macos

One more point worth noting is that all major browsers have dropped support for versions prior to 10.12 (or more):

| Browser         | Supported version |
|-----------------|-------------------|
| Firefox[^7]     | 10.12+            |
| Chrome[^8] [^9] | 10.13+            |
| Safari          | 10.15+ (Safari 12 was the last supported by 10.12) |

[^7]: https://www.mozilla.org/en-US/firefox/104.0.1/system-requirements/
[^8]: https://www.google.com/chrome/
[^9]: https://bugs.chromium.org/p/chromium/issues/detail?id=1322548

A final set of data points is some of the Rust ecosystem:
- [Tauri](https://github.com/tauri-apps/tauri), an Electron alternative written in Rust. [It supports](https://github.com/tauri-apps/tauri#platforms) 10.15+. It has 273k total downloads (26,440/month).
- [Mlua](https://github.com/khvzak/mlua), a set of bindings to Lua. [It supports](https://github.com/khvzak/luajit-src-rs/blob/b53cec68f02cb27f3508cb6bb17a9e6da4717781/src/lib.rs#L104) 10.9+. It has 371k total downloads (22,851/month).
- [mac-notification-sys](https://github.com/h4llow3En/mac-notification-sys). [It supports](https://github.com/h4llow3En/mac-notification-sys/blob/master/build.rs#L11) 10.8+. It has 347k total downloads, and is a dependency of Tauri but works alone too (25,758/month)
- [Nativeshell](https://github.com/nativeshell/nativeshell/), a way to embed Flutter Desktop into a Rust app. [It supports](https://github.com/nativeshell/nativeshell/blob/670f8338323b9f1d26556667a142d141b57e3036/nativeshell_build/src/flutter_build.rs#L356) 10.13+. Its download count is lower compared to the others.
- [Wezterm](https://github.com/wez/wezterm), a cross-platform terminal emulator. [It supports](https://github.com/wez/wezterm/blob/e866e9390aec2f88a1056a92d78dc4a3f737121e/config/build.rs#L60) 10.9+.
- [Espanso](https://github.com/espanso/espanso), a cross-platform text expander. [It supports](https://github.com/espanso/espanso/blob/930bf807b5802218adff3d0a73e339233182e6dc/scripts/build_binary.rs#L85) 10.13+.
- [Alacritty](https://github.com/alacritty/alacritty/), another cross-platform terminal emulator. [It supports](https://github.com/alacritty/alacritty/blob/4bf8f375ef0f5551896a68d6504c08f9576a125f/Makefile#L36) 10.11+.

## iOS specific

According to [Apple's app store stats](https://developer.apple.com/support/app-store/), 82% of all iPhones use iOS 15, and, going back further 96% of devices have iOS 13 at a minimum. Given the proposed increase to iOS 10, this shows that an incredibly small number of devices still run iOS 9 and earlier. This is in stark constrast to something like Android, where old OS versions linger for many years past official vendor support.

Additionally, Apple semi-recently has [begun requiring](https://developer.apple.com/news/?id=2t1chhp3) all mobile apps submited to app store to use XCode 13, with the iOS 15 SDK. This [requires](https://developer.apple.com/support/xcode/) iOS 9 as the minimum deployment target, and iOS 10 in the simulator. A requirement of iOS 10 would also bring the minimum device requirement from the iPhone 4 (2010) to the iPhone 5 (2012). Given Apple's cadence bumping the SDK requirement, iOS 9 will most likely be unsupported in 1-2 years for new app versions.

[Winit](https://github.com/rust-windowing/winit) also [requires iOS 8](https://github.com/rust-windowing/winit/blob/112965b4ffe3405fb7064a49fbe17f081bb7628a/src/platform_impl/ios/app_state.rs#L1024-L1031). It has 3,693,208 total downloads (156,839/month). No other (public) crates seem to define a minimum iOS version beyond what Rust specifies using `IPHONEOS_DEPLOYMENT_TARGET`.

## Possible improvements

Both the standard library and some parts of the compiler would be simplified via this proposal:

- [Signifigant improvements to Apple filesystem API usages](https://github.com/rust-lang/rust/blob/3fdd578d72a24d4efc2fe2ad18eec3b6ba72271e/library/std/src/sys/unix/fs.rs#L1595), due to the addition of many standard UNIX functions.
- [Simplifying stdlib Apple random code](https://github.com/rust-lang/rust/blob/12e4fd0755d7d976d4ee0f2004dc938290752ff7/library/std/src/sys/unix/rand.rs#L214), due to `getentropy` being available on all supported platforms. `/dev/urandom` and `SecCopyRandomBytes` would no longer be needed.
- [Simplfying compiler Apple TLS code](https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/apple_base.rs), due to no longer supporting Apple platforms with no TLS support.
- [Architectually guarantee SSE4.1 for macOS](https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Arch/X86.cpp#L85-L86)
- [Adding TLS support for iOS](https://godbolt.org/z/h5MqMahGj)
- [Simplifying bootstrap for iOS](https://github.com/rust-lang/rust/blob/b32223fec10743af93913c41ec60645d741b0cb6/src/bootstrap/native.rs?q=10.#L729), soley from the new iOS version.
- [Simplifying stdlib Apple clock code](https://github.com/rust-lang/rust/blob/e1b28cd2f16bd5b832183d7968cae3bb9213e78d/library/std/src/sys/unix/time.rs?q=mach_timebase#L144), due to the addition of `clock_gettime`.

On top of that, it brings some other nicities that could be used for future improvements:
- [os_unfair_lock](https://developer.apple.com/documentation/os/os_unfair_lock) to improve some stdlib internals.
- Misc other unifications from better UNIX compatibility.

A [past counterpoint](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Upcoming.20Linux.2FmacOS.2FWindows.20support.20changes/near/287110604) has been that Apple's Swift language [supports](https://www.swift.org/platform-support/) running on back to macOS 10.9 and iOS 7. However, I'm not of the belief this is a fair standard for a static, 3rd-party language like Rust. Swift is directly supported by Apple and therefore can have more OS-level support for backwards compatibility then any other language. This includes [numerous](https://github.com/apple/swift/tree/7123d2614b5f222d03b3762cb110d27a9dd98e24/stdlib/toolchain) [backwards compatibility](https://github.com/apple/swift/tree/7123d2614b5f222d03b3762cb110d27a9dd98e24/stdlib/public/CompatibilityOverride) shims and hot patching of older runtime versions. Since Rust has no underlying runtime provided by the operating system, it should not have the same expectations of extreme backwards compat.

# Mentors or Reviewers

@thomcc - ~~reviewer~~ mentor

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [x] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by thomcc** [comment]
> @thomcc - reviewer

FYI, while I encouraged @BlackHoleFox to write this and provided feedback on an earlier version, I'm not the right person to review (not compiler reviewer or someone who regularly contributes to `compiler/*`). I suspect I can mentor though, since the work needed is presumably fairly minor (it's mostly a change to policy and rustc-target, I think).

**Comment by thomcc** [comment]
I asked this in zulip, without any luck, but is there anything that can be done to push this forward? I would like us not to have to worry about these versions in the stdlib anymore, at the very least.

**Comment by nikic** [comment]
I think we need an FCP for this one, given the public-facing change -- could someone from the compiler team start one? (Or would it be preferred to do that on the PR implementing this change?)

**Comment by wesleywiser** [comment]
I think we should 

@rustbot second

this proposal and then do an FCP on the actual PR.
