### ISSUE TITLE
injecting query results (salsaification)

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#562]
# Meeting proposal info

- **Title:** Allow queries to insert the return value of other queries 
- **Type:** technical
  
# Summary

Allow queries that programmatically insert entries into the query cache for certain keys. This allows queries to return results for keys that they would otherwise not have logic for.

A preliminary implementation including a demo is included in https://github.com/rust-lang/rust/pull/96840, but we'll want to present and discuss this scheme before merging it.

cc @cjgillot

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
We had the meeting

Document: https://hackmd.io/8dZwSvOKR-6TFMTEe8nKJA

Zulip: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202022-11-04.20compiler-team.23562.20inj.2E.20query.20results/near/307977502
