### ISSUE TITLE
Raw pointer alignment checks in debug

### ISSUE THREAD

**Issue by saethlin** [rust-lang/compiler-team#570]
# Proposal

Add a MIR transform which inserts an explicit check that a raw pointer is aligned before it is dereferenced, panicking if it isn't. This transform should only be run when debug assertions are enabled.

I have been slowly working on a draft implementation: https://github.com/rust-lang/rust/pull/98112

See also: https://github.com/rust-lang/rust/issues/54915 https://github.com/rust-lang/rust/issues/51713

# Mentors or Reviewers

@oli-obk has lightly committed to reviewing the existing implementation

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by nikomatsakis** [comment]
I love this!

**Comment by nikomatsakis** [comment]
I'm nominated this for discussion in the lang team meeting: these sorts of user-visible changes feel like sometimes we ought to discuss. That said, I personally have long wanted us to make debug builds more effective at detecting UB, and I approve of steps in that direction.
