### ISSUE TITLE
Move tests out of src

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/compiler-team#573]
# Proposal

Searching code on github only supports positive path filtering (i.e. "include path") whereas having tests inside src requires negative path filtering (i.e. "exclude path"). To make it truly usable we should move tests out of src.

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by petrochenkov** [comment]
The rust-lang/rust repo is currently stuck in mid-transition with `compiler` and `library` already moved from `src` and everything else still staying there.
The test directory is a directory that can also be just moved without any further restructuring.
@rustbot second

**Comment by albertlarsan68** [comment]
A PR is up at rust-lang/rust#106458
