### ISSUE TITLE
New tier-2 target for `wasm32-wasi` + threads

### ISSUE THREAD

**Issue by abrown** [rust-lang/compiler-team#574]
# Proposal

Several of us working on WebAssembly (cc: @alexcrichton, @loganek, @sunfishcode, @sbc100, @AlexEne) have made progress on a WASI proposal to allow spawning threads in WebAssembly programs via a new WASI interface: [wasi-threads]. Several issues related to the proposal are still under discussion, but the core idea is implemented in at least two WebAssembly engines (Wasmtime and WAMR) and a subset of the pthreads API is supported for the C language via [wasi-libc]. I am opening this issue to request adding support for this in the Rust compiler.

Why a new target? [wasi-threads] relies on the WebAssembly [threads] proposal; modules built with threads enabled allow new features such as atomic instructions and shared memories. Not all users will want to allow threads-enabled programs in their environment but still will want to compile to `wasm32-wasi`: after some discussion [here](https://github.com/WebAssembly/wasi-libc/issues/326), we decided to use a new target triple to indicate that a program targets both WASI (including wasi-threads) _and_ the WebAssembly threads feature.

In wasi-libc, this target is currently named `wasm32-wasi-pthread` but this name has not yet been released and could change. I would prefer, for simplicity, that the wasi-libc target and the rustc target were the same, so I can change the wasi-libc one if there are other suggestions here (e.g., `wasm32-wasi-threads`?). Let the bikeshedding begin...

What is more important is whether to approve this proposal: can we add a new target (very similar to `wasm32-wasi`) that allows us to implement wasi-threads in Rust? Some previous work on this includes [getting the atomics build to work](https://github.com/rust-lang/rust/pull/102372); eventually this looks like implementing `Thread::spawn` via `wasi_thread_spawn`. The new target gives us the ability to incrementally fill in the implementation details as wasi-libc and the wasi-threads proposal evolve.

[wasi-threads]: https://github.com/WebAssembly/wasi-threads
[wasi-libc]: https://github.com/WebAssembly/wasi-libc
[threads]: https://github.com/WebAssembly/threads

# Mentors or Reviewers

@alexcrichton

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by abrown** [comment]
I don't think you can yet. I've been waiting for the LLVM 16 support to be incorporated into `rustc` and now that that has happened, I was planning to look at implementing the new `wasm32-wasi-threads` target and `std::thread::spawn`.

**Comment by patrickelectric** [comment]
any update on that ?

**Comment by alexeiaguiar** [comment]
Take a look at these new targets, like this one:

https://doc.rust-lang.org/rustc/platform-support/wasm32-wasip1-threads.html
