### ISSUE TITLE
Store ICE backtraces to disk and point end users at the file location

### ISSUE THREAD

**Issue by estebank** [rust-lang/compiler-team#578]
# Proposal

Modify `rustc`'s panic handler to always store ICE backtraces and the query stack, as well as other minimal debugging-relevant information (platform, `rustc` version) to a file on disk. Modify the presented output to be less intrusive (we would no longer print out a wall of inscrutable text unless `RUSTC_BACKTRACE=full` is set and hope people notice the instructions) and include instructions on how to find the file and submit a ticket. When  `RUSTC_BACKTRACE=full` isn't set and a backtrace wouldn't be printed, we'd print the backtrace to disk.

# Mentors or Reviewers

@estebank

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

I've [created a draft PR to experiment on what was technically feasible](https://github.com/rust-lang/rust/pull/106691) and I am satisfied with the results.

**Comment by compiler-errors** [comment]
Hm, well seems like there's a bit more discussion in the zulip thread. Perhaps we should pause this MCP for now, at least until discussion has settled?

**Comment by apiraino** [comment]
@compiler-errors No problem, I'll tentatively revert the FCP until the discussion settles. Please feel free to second again (or anyone else) later on.

@rustbot label -final-comment-period
