### ISSUE TITLE
Ignore PhantomData not in Drop impl for dropck

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/compiler-team#586]
# Proposal

Simply ignore PhantomData for dropck, allowing the following to compile: (note that it compiles if you take out the `String`.)

```rust
use core::cell::Cell;
use core::marker::PhantomData;

struct Dropper<T>(T);

impl<T> Drop for Dropper<T> {
    fn drop(&mut self) {}
}

struct Foo<'a>(PhantomData<Dropper<Cell<&'a Foo<'a>>>>, String);

fn main() {
  fn make_selfref<'a>(x: &'a Foo<'a>){}
  let x = Foo(PhantomData, String::new());
  make_selfref(&x);
}
```

- - -

This is an user-facing change but mostly we just wanna see a crater run for this. Ignoring it "not in Drop impl" basically boils down to how it's currently used with `#[may_dangle]` and we don't wanna break that, but the above code is not unsound or anything so it seems like forbidding it is an oversight.

see also https://github.com/rust-lang/rust/issues/102810

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by oli-obk** [comment]
Closing as this is a language change proposal, so the compiler team can't make decisions on this MCP. As mentioned in the zulip thread, please start a new thread in the lang team zulip stream
