### ISSUE TITLE
P-high review for 2023 Q1

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#590]
# Meeting proposal info

- **Title:** 2023 Q1 P-high review
- **Type:** technical
  
# Summary
In compiler-team https://github.com/rust-lang/compiler-team/issues/479, we agreed that we would have a roughly quarterly attempt to process the backlog of P-high issues.

We should do another in 2023 Q1. My hope is that we can fit into a single meeting this time around, since we got through the whole backlog by the end of 2022 Q4.

We did one in 2022 Q1, both before and after the steering meeting for https://github.com/rust-lang/compiler-team/issues/479, see https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/reviewing.20P-high.20issues.202022.20.28Q1.29/near/268563880 for that discussion. We did another in 2022 Q2, I think (still need to find a link for that.) and again in 2023 Q3/Q4 (it spilled out over several weeks)
 
So we should do another in 2023 Q1. My hope is that we can fit into a single meeting this time around, since we got through the whole backlog by the end of 2022 Q4.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by pnkfelix** [comment]
As announced on https://blog.rust-lang.org/inside-rust/2023/02/10/compiler-team-feb-steering-cycle.html, we'll be having this meeting on 2023-03-03

@rustbot label: +meeting-scheduled

**Comment by apiraino** [comment]
> We did another [P-high review] in 2022 Q2

Probably this one https://hackmd.io/F8I68mHBRKmVGd234Dzeig

**Comment by apiraino** [comment]
Closing as this review happened, here's the report:
https://hackmd.io/h0-EDjrdREmTcG6X6-vKlA
