### ISSUE TITLE
Use `ControlFlow` in HIR `Visitor`

### ISSUE THREAD

**Issue by Jarcho** [rust-lang/compiler-team#597]
# Proposal

Currently early returns from visitors are handled by storing a flag or `Option` type and checking if the result has been found at the start of `visit_*` methods. The proposal is to have all `visit_*` functions return `ControlFlow<Self::BreakTy>` the same way `TypeVisitor` does.

Most examples of early returns are from clippy, where this is the most use of visitors. There are a not insignificant number of examples in rustc as well.

Related PR: rust-lang/rust#108598

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by pnkfelix** [comment]
@rustbot second

From the associated [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Use.20.60ControlFlow.60.20in.20HIR.20.60Visitor.60.20compiler-team.23597/near/338914728), it is clear that there is support for doing *something* in this space.

Its possible that the actual implementation that lands won't use `ControlFlow`, but rather some other trait, or perhaps something else like an associated type, and that is **fine**, we don't need to flesh out all the details in this MCP ahead of time.
