### ISSUE TITLE
Add `--print=all-target-specs-json` unstable flag

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/compiler-team#600]
# Proposal

This MCP proposes to add the unstable `--print=all-target-specs-json` compiler flag in addition to the existing unstable `--print=target-spec-json` flag. The flag will output to the standard output the JSON representation of *all* builtin target specs, emitting a (sorted) map with the target name as the key and the target spec as the value:

```json
{
  "aarch64-apple-darwin": {
    "abi-return-struct-as-int": true,
    "arch": "aarch64",
    ...
  },
  "aarch64-apple-ios": {
    "abi-return-struct-as-int": true,
    "arch": "aarch64",
    ...
  },
  ...
}
```

This is needed by https://github.com/rust-lang/rust/pull/108905, as it needs to know the details of all targets in order to validate compiletest directives like `only-windows` and `ignore-x86_64`. The alternative of invoking `--print=target-list` and then iterating each target with `--print=target-spec-json` takes around 5 seconds on my machine, which is not great.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by Mark-Simulacrum** [comment]
@rustbot second

This is an unstable flag and we can remove it if we decide there's a better alternative. For now I think this makes sense to add.
