### ISSUE TITLE
2024: Decrease debuginfo generated by  `-Cdebuginfo=1`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/compiler-team#613]
# Proposal

In the 2024 edition, change `-C debuginfo=1` from being an alias for `-C debuginfo=limited` to an alias for `-C debuginfo=line-tables-only`.

For a long time, the available debuginfo options have been `debuginfo=0`, 1, or 2. The documentation said that 0 meant no debuginfo, 1 meant line tables, and 2 meant full debuginfo. Unfortunately that wasn't quite true - `debuginfo=1` also generated full debuginfo for the module as well as line tables, which in some cases (e.g. https://github.com/rust-lang/rust/pull/104968#issuecomment-1474758709) more than doubled the size of the debuginfo.

Due to backwards compat concerns, I added a new option, `-C debuginfo=line-tables-only` to decrease the debuginfo further, rather than changing the meaning of the existing flag (https://github.com/rust-lang/rust/pull/109808, https://github.com/rust-lang/cargo/pull/11958). I think this is in nearly all cases the intended meaning of the flag. I would like to make `-C debuginfo=1` mean `debuginfo=line-tables-only` in the 2024 edition, which both gives people plenty of time to hear about the change and means that it's opt-in rather than breaking.

# Mentors or Reviewers

I'm happy to mentor this work myself, the code itself should be fairly simple.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
Closing MCP as not accepted
