### ISSUE TITLE
Cell Broadband Engine SPU support

### ISSUE THREAD

**Issue by nrabulinski** [rust-lang/compiler-team#614]
# Proposal

I'd like to implement support for the Cell SPU in Rust as I'm currently working in my spare time on making Rust a first-class language for the PS3. The Cell PPU is pretty much a generic PPC target which shouldn't require any changes to Rust, but the SPU is a completely separate architecture which will need major changes in form of inline assembly, most likely changes to the object crate, rust_codegen_ssa and more. The caveat here is that the SPU target has been dropped from LLVM in version 3.3 (ref: https://releases.llvm.org/3.3/docs/ReleaseNotes.html#non-comprehensive-list-of-changes-in-this-release) and from GCC in version 10 (ref: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=7ee1594e0ebf75195f6eb5e23516ae12618c9f82&utm_source=anzwix) which begs the question - should changes specific to an architecture, which is not supported by LLVM (and most likely won't be given that it has been removed) nor `rustc_codegen_gcc` which supports GCC 12 and up, be committed upstream.
There has been an argument made that we have already merged changes specific to architectures which require a custom backend, namely the SPIRV for rust-gpu, but it still warrants an MCP and a discussion.

# Mentors or Reviewers

Not sure who can review or mentor as I want to take on the task of implementing it but haven't worked on any compiler internals before.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by wesleywiser** [comment]
Hi @nrabulinski, thanks for submitting your proposal. We discussed this in today's compiler team meeting and the consensus in the meeting and in the Zulip stream for this proposal was that we would prefer not to take "major changes" to support a target that has been dropped from both LLVM and GCC. 

However, if there are smaller scale refactorings or changes that make sense on their own, independent of supporting the Cell SPU, we would be happy to review those!
