### ISSUE TITLE
Add a new `--crate-version` flag to rustc

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-lang/compiler-team#622]
# Proposal

## The problem

`rustdoc` relies on its `--crate-version` flag to know the version of the crate it is generating documentation for.  
There is no equivalent source of information, though, for the version of its dependencies.

This causes issues when multiple versions of the same crate are listed as direct dependencies (via renames) of the crate we are documenting—e.g. [it becomes impossible to find out where items are coming from](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Identifying.20external.20crates.20in.20Rustdoc.20JSON/near/352551996).

## The proposed solution

Add a `--crate-version` flag to `rustc`.
The value would be provided by `cargo` and then captured as part of the .rlib metadata, which would in turn make it available to `rustdoc`, as well as other parts of the compiler that might benefit from it (e.g. diagnostics, such as [version mismatches](https://github.com/rust-lang/rust/issues/110055) which currently limit themselves to `perhaps two different version of CRATE_NAME are being used?`).

# Mentors or Reviewers

A mentor would definitely be appreciated, I never touched any of the code involved here.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [x] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
reverting the closing to let some time to discuss the design

**Comment by LukeMathWalker** [comment]
Closed in favour of https://github.com/rust-lang/compiler-team/issues/635
