### ISSUE TITLE
Finalize initial version of experts map

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/compiler-team#63]
Based on [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/learning.20WG/near/163673962), work out what else needs changed with the initial version of the experts map and move it into this repository.

**Comment by amanjeev** [comment]
Current compiler team map https://hackmd.io/Izvor8KZRiqUgcUyd2CYTw

**Comment by spastorino** [comment]
I've just opened a new Zulip thread to have more people polishing the map https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/expert.20map

**Comment by eddyb** [comment]
cc https://github.com/rust-lang/infra-team/issues/24 @pietroalbini 
It would be great to have this in a machine-readable format, including file paths, not just descriptions.

**Comment by mark-i-m** [comment]
It seems to be missing Chalk. Also, it is not clear if `src/librustc/traits`, `src/librustc_traits` means "traits in general" or "specifically those crates/modules".

**Comment by spastorino** [comment]
@mark-i-m that row is about traits in general, @nikomatsakis idea was to list the directories where that knowledge is contained. I've just opened this https://github.com/rust-lang/compiler-team/pull/74 and with the machine readable file as @eddyb suggested we will be able to maybe do stuff like r? RLS and have RLS people from there assigned or in PRs using the directories bots could use some kind of heuristic to atomatically decide what area of knowledge is the PR about and assign someone from there. If that was not entirely the idea, just throwing it as one possible idea :).
