### ISSUE TITLE
Use `FieldIdx` all the way down

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/compiler-team#639]
# Proposal

While doing some `IndexVec` cleanups I've noticed that `FieldIdx` is converted a lot to and from integer form because a lot of code still uses `usize`s. I propose to use `FieldIdx` in as much places as possible, as it improves readability and robustness.

The "problem" here is that once you change things in one place, it requires changes in adjacent places, which requires changes in adjacent places, etc. This can be somewhat annoying to review. I haven't finished this refactor and it already touches quite a bit of code, so wanted to check with a MCP before finishing the work here.

Crates that seem to be affected so far:
- `rustc_codegen_ssa`
- `rustc_const_eval`
- `rustc_middle`
- `rustc_target`

# Mentors or Reviewers

?

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by compiler-errors** [comment]
cc #606, noting here that an MCP was already approved along the same lines

**Comment by wesleywiser** [comment]
Personally, I would consider #606 sufficient alignment to start doing this (thanks @compiler-errors for pointing to that accepted MCP!) but just to be super safe:

@rustbot second
