### ISSUE TITLE
Add support for the riscv64-linux-android target

### ISSUE THREAD

**Issue by chriswailes** [rust-lang/compiler-team#640]
# Proposal

The Android team would like to add support for the `riscv64-linux-android` target.  We've been building and testing a local version of this patch for several releases and are ready to upstream these changes to support experimental development for the target.

# Mentors or Reviewers

chriswailes

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by Amanieu** [comment]
My understanding is that Android will end up requiring a larger set of features than the base GC RISC-V profile. Does this target intend to track the upstream target requirements, in which case this should be considered more of a "beta" target until the exact feature requirements for Android are nailed down?

**Comment by chriswailes** [comment]
You are correct on all accounts.  Is "beta" an alternative to "Tier 3"?

**Comment by the8472** [comment]
Wasi is switching to a `-preview<number>` suffix. See #607

**Comment by riking** [comment]
"Target is beta" is something you would describe in the target support document.
