### ISSUE TITLE
Add illumos Tier3 targets

### ISSUE THREAD

**Issue by Toasterson** [rust-lang/compiler-team#644]
# Proposal

In the illumos community we have several CPU Architectures which are not in our main supported Builds, but they might become supported or endoresed depening on the developments in the Chip market, as can be seen by the popularity of ARM Chips. Even if our platform support will be limited to specific devices (RPI4/Quemu/bHyve) there are use cases that benefit from native binaries being available even now. Considering how many developers now have access to that architecture some use cases for ARM binaries and ARM rust builds are already present.

At this point in time we are only interested in Tier 3 so that we don't have to carry patches in the compiler for when we want to build toolchains or cross toolchains for us and can distribute upstream rust compiler packages for those architectures.

These targets will have some limitations, as one will need a proper GCC and linker installed on the system. Our linker is part of the illumos-gate repository and open source. As I understnad the Tier policy this is ok for Tier 3.

The Architectures that currently are in this experimental stage is aarch64.

We are only interested in having the definitions placed in the code and not additonal requirements for these three architectures.

The currently open PR is https://github.com/rust-lang/rust/pull/112936

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

**Comment by workingjubilee** [comment]
@Toasterson Are you available on Zulip to discuss this?

Are you aware of the [Target Tier Policy]?

Are you agreeing to be the target maintainer for all of these?

Are you sure you wish to agree to be the only official SPARC64 maintainer since the institution of the target tier policy that guaranteed that targets require a known maintainer associated with them?

[Target Tier Policy]: https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy

**Comment by Toasterson** [comment]
I am unable to add to the discussion on Zulip as the "Stream" there is closed to me. Although I only just signed up so it might be that you need to enable my account.

In general unless otherwise stated all illumos targets are usually to be assumed to be maintained by the illumos developers. But if you need details I can arrange that we get it sorted.

I am unaware nor able to find any other inforamtion to SParc64 support other than the Target tier policy which shows several Operating systems in Tier 3 and two in Tier 2. The target `sparcv9-sun-solaris` even mentions illumos support and is Tier 2.

**Comment by davidtwco** [comment]
@rustbot second

This seems reasonable and we should have probably seconded it sooner, discussion in Zulip looks resolved :)
