### ISSUE TITLE
Windows support schedule 2024

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/compiler-team#651]
Currently Windows 7 and 8 are listed as Tier 1 supported platforms. However, this has not been true for a long long time. We simply do not have the testing infrastructure. And with so much software now abandoning Windows 7 and 8 (everything from Git to Go to every major browser), continuing to provide the little support that we do is only getting more difficult. There is also a lack of vendor support for these targets.

This proposal aims to raise the minimum supported Windows version of current targets to Windows 10 (first released in 2015) during 2024. But it also leaves open the door for new targets that can commit to broader support, By having a separate target we can ensure there are people specifically tasked with supporting legacy versions of Windows.

# Proposal

Rust 1.75 will be the last to officially support Windows 7, 8 and 8.1. Support for Windows versions before 10 will end in February 2024 with Rust 1.76.

Support for Windows 7 and 8 may continue beyond these dates through the creation of new "legacy" targets for older Windows versions. Individuals or organisation(s) who can commit to providing some level of legacy testing and support should go through the normal process for [creating new targets](https://doc.rust-lang.org/rustc/target-tier-policy.html#adding-a-new-target).

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by kennykerr** [comment]
For what it's worth, this is good news for Rust.

**Comment by workingjubilee** [comment]
32-bit x86 Windows **is** supported as a tier 1 platform for Rust.

It is simple, and already stated in Chris Denton's post: We do not have access to test environments for Windows 7 anymore. This is because the OS images we would use for our test suite for Windows 7 have effectively disappeared, along with Microsoft's official support for those images. So we are not testing it. We _are_ testing on Windows 10. As we are not testing Windows 7, we are not giving it tier 1 support, which is defined as passing our test suite for *every* merge.

If you want working software, then you should probably want us to actually say what Windows version we support.

**Comment by zhuxiujia** [comment]
I don't agree with this decision. The existing devices in Win7 and 8 are very large, which is definitely a wrong decision. I really don't understand why the core team is so stubborn

**Comment by the8472** [comment]
> This issue is not meant to be used for technical discussion. There is a Zulip [stream](https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Windows.20support.20schedule.202024.20compiler-team.23651) for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.

☝️

**Comment by han1548772930** [comment]
It would be very bad if Rust lost users of Windows 7 and 8

**Comment by RalfJung** [comment]
Cc https://github.com/rust-lang/rust/pull/118150 since it is relevant for this thread: there are tier 3 targets for Windows 7.
