### ISSUE TITLE
Add option to pass environment variables

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/compiler-team#653]
# Proposal

Add a new `--env VAR=VALUE` option which injects environment variables into the program, allowing them to be read by the `env!` and `option_env!` macros and from `proc_macro_tracked_env`.

An initial implementation (not merged) was done in https://github.com/rust-lang/rust/pull/94387.

# Mentors or Reviewers

@bjorn3 and @jyn514 were the ones who reviewed the original PR so at least tagging them here as potential mentors/reviewers.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by dtolnay** [comment]
Prior art: https://github.com/rust-lang/rfcs/pull/2794

**Comment by jsgf** [comment]
Yeah very in favour of this, but it needs to have a way to also remove all process-environment variables, so that you can entirely specify the logical environment on the command line.

**Comment by GuillaumeGomez** [comment]
Your RFC seems more complete. Any idea why it was approved yet?

**Comment by jsgf** [comment]
> Any idea why it was [not?] approved yet?

It just needs to be driven. There are no objections, but I don't think it's got much attention. I'm happy to take it up again, esp if we have multiple independent use-cases for the functionality.

**Comment by jsgf** [comment]
I updated my impl in https://github.com/jsgf/rust/tree/env-sandbox

**Comment by GuillaumeGomez** [comment]
Going to start working on it next week probably.

**Comment by jsgf** [comment]
How does this relate with https://github.com/rust-lang/rfcs/pull/2794? This seems like a strict subset, but it's not clear to me how the issues raised on my RFC are resolved here (eg interaction with tracked vars and proc macros). Also there's the question of how env vars containing paths are handled, though that's a broader question.

**Comment by GuillaumeGomez** [comment]
I completely forgot about it since previous comment. I'll resume work on it as soon as possible as I said.

**Comment by the8472** [comment]
> (for performance reasons AFAIK)

The fork/vfork difference? I think glibc's posix_spawn will still use vfork even if a new environment is passed.

**Comment by eli-schwartz** [comment]
I forget offhand the exact details, but I seem to recall that ninja did not want to commit to supporting this on Linux because it would be inconsistent with Windows, and they weren't sure it could be done fast on Windows.

It was a strange argument to me personally, because I would have thought the answer is "support it everywhere, and document that if you actually make use of the functionality to set environment variables in the subprocess AND you are using Windows, it will result in minor performance penalties as opposed to fatally failing because the required variable was not set".

**Comment by Nilstrieb** [comment]
I kindly ask you to move to the zulip thread linked in the first comment instead of discussing it here to avoid sending out notifications to everyone :)
