### ISSUE TITLE
How to grow new experts in code that has few or none

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/compiler-team#654]
# Meeting proposal info

- **Title:** How to grow new experts in code that has few or none
- **Type:** it's complicated
  
# Summary

We have some parts of the compiler code base that lack active experts. This leads to problems when it comes to e.g. reviewing PRs for that part of the code base.

@wesleywiser and @pnkfelix were recently discussing strategies for addressing this. We want to bring them to the attention of the broader compiler team for discussion.

@pnkfelix plans to write a doc or at least some notes to drive the meeting if/when it is scheduled.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by wesleywiser** [comment]
Meeting was held here https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202023-08-11.20growing.20new.20experts.20compiler-team.23654

**Comment by apiraino** [comment]
meeting happened, so I think this can be closed
