### ISSUE TITLE
External Dependency Timelines

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/compiler-team#663]
# Meeting proposal info

- **Title:** External Dependency Timelines
- **Type:** non-technical
  
# Summary

Sometimes changes in rustc depend on support in external tooling, such as name mangling or debuginfo. 

We currently have no defined policy on how long to wait before merging or enabling changes in these areas. As a consequence, changes waiting on external dependencies can get blocked as nobody is quite sure when "long enough to wait" is.

https://hackmd.io/@rust-compiler-team/r1tHfYD2n

# About this issue

This issue corresponds to a meeting proposal for the compiler team [steering meeting][]. It corresponds to a possible topic of discussion. You can read more about the [steering meeting procedure here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel" regarding the proposal, and not as a place to discuss the technical details. Feel free to subscribe to updates. We'll post comments when reviewing the proposal in meetings or making a scheduling decision. In the meantime, if you have questions or ideas, ping the proposers on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by apiraino** [comment]
meeting happened on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202023-09-01.20external.20dependency.20timelines/near/388529627), here the [notes](https://hackmd.io/@rust-compiler-team/r1tHfYD2n).
