### ISSUE TITLE
Support larger sizes in rmeta tables and incr comp alloc offsets

### ISSUE THREAD

**Issue by saethlin** [rust-lang/compiler-team#666]
# Proposal

Rustc stores a lot of lengths in `u32`, which reduces the size of data structures and on-disk formats that contain these lengths. But this strategy limits the space of programs that can be compiled. In general, this is a gamble that our user base will benefit more from the performance improvement of picking a small fixed-size type than the implementation limitation this imposes will cause trouble.

We have a few reports of running into the `u32` limit for rmeta table offsets and incr comp allocation offsets:

* https://github.com/rust-lang/rust/issues/103607
* https://github.com/rust-lang/rust/issues/112934
* https://github.com/rust-lang/rust/issues/76037
* https://github.com/rust-lang/rust/issues/95780
* https://github.com/rust-lang/rust/issues/111613

This is a proposal to find a way to lift the implementation limitation imposed by using `u32` in these two places, and thus be able to compile the programs reported in these issues.

Current implementations of these are:
* https://github.com/rust-lang/rust/pull/113562
* https://github.com/rust-lang/rust/pull/113542

While the goal of this MCP is to support compiling more programs, it is important that the additional space of supported programs not impose a measurable cost on the average user according to our benchmark suite. In that sense, the perf implications of solutions to this MCP should be evaluated on their own, as opposed to as if they are the cost of adding a feature.

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by WaffleLapkin** [comment]
Closing as accepted (we should maybe automate "close after 10 days"...)
