### ISSUE TITLE
Condemn `asmjs-unknown-emscripten` to push a boulder up a hill for eternity

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/compiler-team#668]
# Proposal

I believe this is [the traditional punishment](https://en.wikipedia.org/wiki/Sisyphus) for those that [cheat Death and find Death catching up with them again](https://github.com/rust-lang/rust/issues/51856).

The target support code will be ~~placed beyond the reach of mortal hands~~ removed, because it is [impossible to make the asmjs target functional again with any recent version of emscripten](https://github.com/emscripten-core/emscripten/issues/18013).

# Mentors or Reviewers

I recommend Thanatos, but any of the Chthonic gods will do.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by RalfJung** [comment]
I'm quite amused but unfortunately I don't know what is actually being proposed. :joy:

**Comment by workingjubilee** [comment]
Well, the `asmjs-unknown-emscripten` target is de facto dead, seeing as how it doesn't perform basic functions like "emitting object code". It is only "alive" i.e. in the rustc codebase and can be "used" for any purpose because apparently Death has been prevented from reaping it, somehow, so the proposal is to fix that by moving the target support code from the rustc codebase to Tartarus.

This would hypothetically negatively impact anyone who wishes to use the `asmjs-unknown-emscripten`, but so would the fact that the target is in truth only an unliving ghoul that does not emit the correct object code that is supposed to be runnable by a conventional JavaScript interpreter, but rather wasm32 instructions. Presumably if any users actually relied on that, someone would have at least complained loudly in the past 3 years.

**Comment by workingjubilee** [comment]
It should be noted this target is **not** tier 3. Some people seem confused on that.

It is **tier 2**. Y'know, like real platforms? Like `aarch64-apple-darwin`?

So permitting it to exist in the Rust codebase is functionally a statement that we are okay with targets that e.g. emit 64-bit Arm instructions when they're supposed to emit x86 instructions. Or, say, Sparc instead of Arm. If this state of affairs is permitted to continue, this is effectively a statement that tier 2 targets are effectively meaningless definitions of "support".

I have been admonished to adhere to "process" however, so I am filing a ridiculous proposal to rectify a ridiculous state of affairs instead of simply submitting a PR to remove the target immediately, which is what I would prefer to do. There is certainly a joke here, but it started well before I wrote anything into the "post an issue" box.

**Comment by wesleywiser** [comment]
@workingjubilee Could you edit your proposal to mention specifically whether `asmjs-unknown-enscripten` should be demoted to [~Cocytus~](https://en.wikipedia.org/wiki/Cocytus) Tier 3 or removed from the compiler and standard library entirely? I assume you would prefer the latter but it would be best to confirm.

Thanks! 🙂
