### ISSUE TITLE
Add a system for registering function pointers similar to registering queries

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#678]
# Proposal

We have some queries, that should not be queries, but only are queries, because their body needs to live in a crate other than `rustc_middle`. Queries are overkill for this and have various problems if the arguments are not incremental/query-cache safe (see https://github.com/rust-lang/rust/pull/115819). Instead I propose to add a way to add function pointers to [`Providers`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/query/struct.Providers.html) that will then get stored in `TyCtxt` and have a method generated on the `TyCtxt` that invokes the function pointer.

# Mentors or Reviewers

The implementation should be fairly straight forward, so anyone from T-compiler or T-compiler-contributors

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by RalfJung** [comment]
So, the 10-day period is already over then, since it started 2.5 years ago? ;)

**Comment by apiraino** [comment]
I would close as "duplicate" (if such a label makes sense)
