### ISSUE TITLE
Require `--known-broken-llvm` flag for x.py to skip codegen tests on old LLVM

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/compiler-team#687]
# Proposal

Rust usually ships with its own version of LLVM. We often carry patches for known LLVM issues, and corresponding codegen tests. However, we also support people building Rust against system LLVM without those patches, and even against older versions of LLVM. Our support there is so good that we even ensure that `./x.py test codegen` (and the rest of the test suite) still passes -- we automatically skip the tests that we know are broken.

However, I'd argue we are a bit *too good* at supporting anything but our own patched LLVM. We know that those other versions of LLVM have bugs, but the people that build rustc against system LLVM are likely not aware of this problem. Even when they run all the tests, everything still passes!

As a small roadbump in our support for system LLVM, I propose that we have `x.py test codegen` always run the tests that check for codegen bugs that are fixed in our latest LLVM. After all, the point of the tests is to ensure that this build of Rust passes our quality standards, and if old LLVM causes miscompilations on such code, then it doesn't pass our quality standards! Miscompilation bugs often subvert our entire safety story, albeit usually only in extreme corner cases. Therefore `./x.py test codegen` *should* fail on such a build. To continue supporting system LLVM, we can provide a flag or env var that must be set to skip these tests. (Tests that check whether certain optimizations fire can continue to be skipped automatically, or we can decide we also want to treat them the same way as miscompilation tests and require the flag.)

Distros will likely continue to use system LLVM and just set the flag (if they are running the tests at all), but at least now they can't claim that they haven't been warned that they are shipping a sub-standard Rust build to their users. Maybe they'll even pick up our patches and integrate them into their system LLVM and get the tests to pass!

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention them
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
@rustbot concern codegen-tests-are-for-new-optimizations

Registering concern from @nikic ([Zulip note](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Require.20.60--known-broken-llvm.60.20flag.20for.20x.2E.E2.80.A6.20compiler-team.23687/near/401529152)):
> Codegen tests that are limited to new LLVM versions are almost always about new optimizations, not miscompilation fixes. We typically do not add codegen tests for LLVM miscompilations.
