### ISSUE TITLE
Introduce perma-unstable `wasm-c-abi` flag

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/compiler-team#703]
# Proposal

Currently Rust uses a non-spec-compliant ABI for `extern "C" fn` when compiling to `wasm32-unknown-unknown`. Unfortunately, as a large part of the Rust ecosystem relies on `wasm-bindgen`, which didn't support the spec-compliant ABI, switching to the spec-compliant ABI was problematic as it would break a lot of code out there.

With `wasm-bindgen` v0.2.88, it now supports the spec-compliant ABI, so hopefully some day in the future Rust can switch to this ABI. In the meantime it would be important for users to test this new ABI, which is the purpose of this MCP: to introduce a new flag which switches to this new ABI when targetting `wasm32-unknown-unknown`.

This flag would be perma-unstable, as there is no point to stabilize it and then just deprecate it when the new ABI becomes the default.

Related issue: https://github.com/rust-lang/rust/issues/71871
Implementation PR: https://github.com/rust-lang/rust/pull/117919

**Comment by liamrosenfeld** [comment]
I am such a massive +1 on this proposal. This incompatibility has been a major thorn in my side for over a year, so addressing it as soon as possible by adding a flag until eventually making it default would be amazing.

I noticed it has been a while since something has happened with regard to the implementation PR. If there is anything I could do to help move the landing process along, just let me know.

**Comment by daxpedda** [comment]
> I noticed it has been a while since something has happened with regard to the implementation PR. If there is anything I could do to help move the landing process along, just let me know.

The implementation is done, this is just waiting for a review by the team.

**Comment by RalfJung** [comment]
> Currently Rust uses a non-spec-compliant ABI when compiling to wasm32-unknown-unknown.

Clarification: you are specifically talking about `extern "C"` functions here, right? The ABI for `extern "Rust" fn"` (aka plain `fn`) is intentionally unspecified and unstable.

**Comment by oli-obk** [comment]
Please keep the conversation in the zulip thread linked in https://github.com/rust-lang/compiler-team/issues/703#issuecomment-1851065476

**Comment by jackh726** [comment]
@rustbot second

This will need a tracking issue. This second is also predicated on the overall plan of moving towards a spec-compliant ABI continues as expected. If that changes, the flag should be removed (or at least reevaluated!)
