### ISSUE TITLE
uplift some -Zverbose calls and rename to -Zverbose-internals

### ISSUE THREAD

**Issue by jyn514** [rust-lang/compiler-team#706]
# Proposal

right now, `--verbose` has exactly one effect, which is to print more information for `--version`: https://github.com/rust-lang/rust/blob/558ac1cfb7c214d06ca471885a57caa6c8301bae/compiler/rustc_driver_impl/src/lib.rs#L884

this seems kind of silly. there are lots of other places where the compiler adds more info based on `-Z verbose`. some of these are quite useful to show in diagnostics, for example showing full types in a type error rather than eliding similar types with `_`. it would be nice to display those when `--verbose` is passed.

furthermore, it's confusing to have both `--verbose` and `-Z verbose`. i suggest renaming the internal flag (perhaps `-Z verbose-internals` makes it clear that it's not meant to be useful for anyone but compiler devs?).

```
; rg '\.verbose\(' compiler -l
compiler/rustc_driver_impl/src/pretty.rs
compiler/rustc_middle/src/mir/pretty.rs
compiler/rustc_middle/src/ty/generics.rs
compiler/rustc_middle/src/ty/print/pretty.rs
compiler/rustc_hir_typeck/src/expr.rs
compiler/rustc_infer/src/traits/structural_impls.rs
compiler/rustc_query_impl/src/plumbing.rs
compiler/rustc_infer/src/infer/error_reporting/mod.rs
```

# Mentors or Reviewers

@compiler-errors

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by estebank** [comment]
Follow @compiler-errors' guidance from [the zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/uplift.20some.20-Zverbose.20calls.20and.20rename.20to.E2.80.A6.20compiler-team.23706).

@rustbot second
