### ISSUE TITLE
Add -Z direct-access-external-data

### ISSUE THREAD

**Issue by heiher** [rust-lang/compiler-team#707]
# Proposal

Some architectures, such as LoongArch, do not support copy relocation and are not expected to support it in the future. Consequently, regardless of whether the relocation model is `static` or `pic`, direct access to external data should be avoided, and indirect access through the GOT is recommended. However, certain special cases, such as the Linux kernel, require different approaches for accessing external data in `vmlinux` and `modules`. Therefore, I propose introducing the Clang's [`direct-access-external-data`](https://reviews.llvm.org/D92633) option into Rustc.

Option `-Z direct-access-external-data` controls how to access symbols of external data. 

Supported values for this option are:

- `yes` - Don't use GOT indirection to reference external data symbols.
- `no` - Use GOT indirection to reference external data symbols.

If the option is not explicitly specified, different targets have different default values. (Equivalent to the default behavior before this)

For example:

```rust
extern "C" {
    static VAR: i32;
}

#[no_mangle]
pub fn get() -> i32 {
    unsafe { VAR }
}
```

direct-access-external-data=yes
```llvm
@VAR = external dso_local {{.*}} global i32
```

direct-access-external-data=no

```llvm
@VAR = external {{.*}} global i32
```

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**Comment by Nilstrieb** [comment]
Yet another unstable codegen flag thrown into the seas of unstable codegen flags... but it seems useful, so let's not block this on figuring out what to do with them in general. No stability guarantees, so we can always change it in the future.
@rustbot second

**Comment by heiher** [comment]
@Nilstrieb Hello, Could you mark it accepted? Thanks.

**Comment by Nilstrieb** [comment]
@apiraino usually closes them after a while
But I can do it for you
@rustbot label -final-comment-period +major-change-accepted
