### ISSUE TITLE
Compiler-team RFC guidelines appear to be out of date

### ISSUE THREAD

**Issue by ehuss** [rust-lang/compiler-team#708]
The guidance at https://github.com/rust-lang/rfcs/blob/master/compiler_changes.md for filing RFCs appears to be quite old and doesn't contain all the detail about how the compiler team seems to operate these days.

* "Where there is significant design work for the implementation of a language feature, the preferred workflow is to submit two RFCs" I'm not sure I've ever seen this happen.
* It doesn't mention the MCP process.
* Most of the changes that "need an RFC" I assume would use an MCP nowadays.

Would someone be willing to update the guidance, or point the link somewhere that better reflects on how compiler changes should be proposed?

**Comment by Nilstrieb** [comment]
I updated the guide with what I feel like is roughly accurate today.
