### ISSUE TITLE
Support debug fission using -Csplit-debuginfo=post-link

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/compiler-team#721]
# Proposal

On macOS and Windows `-Csplit-debuginfo=packed` puts all debuginfo in a separate file. This avoids leaking sensitive information into release executables while still allowing debugging with those debuginfo files and reduces file size. On Linux however we make use of dwarf split debuginfo, which puts a fair amount of information into the executable itself, leaking sensitive data like build paths, and increases the size of executables. Instead I propose to add an option to use debug fission where the debuginfo sections are copied out of the executable into a separate file and buildid is used to be able to locate the right debuginfo file. This is what all major linux distros use for debuginfo. This disadvantage over the current scheme is longer linking time, but for local development `-Csplit-debuginfo=unpacked` is a better choice anyway, which I propose to keep using dwarf split debuginfo as is. This way `-Csplit-debuginfo=unpacked` is the best choice for local development and the new `-Csplit-debuginfo=post-link` is the best choice for release builds across all platforms that support the respective options. `-Csplit-debuginfo=post-link` would be equivalent to `-Csplit-debuginfo=packed` on Windows and macOS.

# Mentors or Reviewers

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by michaelwoerister** [comment]
@rustbot second

Thanks, @bjorn3!
