### ISSUE TITLE
Put "checks that detect UB" under their own flag below `debug_assertions`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/compiler-team#725]
# Proposal

@saethlin has been working on adding more and more checks to rustc and the standard library that can detect widespread uses of UB. Currently, they are all controlled by `-Cdebug-assertions`/`cfg(debug_assertions)`. I would argue that similar to the existing `-Coverflow-checks`/`cfg(overflow_checks)`, it is worth having a knob that can separately control them. While they generally have fairly little overhead, in some cases they can [hurt a lot](https://github.com/rust-lang/rust/issues/121245#issuecomment-1962891655). And vice versa, maybe someone wants to turn on just these checks but not all the checks for more "harmless" bugs.

So I suggest we add a new flag, `-Cub-checks`/`cfg(ub_checks)`, that behaves like `overflow_checks`: it defaults to match `debug_assertions` but can be overwritten separately. Initially it would be unstable as `-Zub-checks`, and `cfg(ub_checks)` would not be stabilized before `cfg(overflow_checks)`.

When this was discussed [previously](https://github.com/rust-lang/compiler-team/issues/625), a lot was talked about whether this should be grouped with the sanitizers. However, currently this is controlled entirely by `-Cdebug-assertions`, so just splitting up that flag in the established way seems to make most sense to me. In the end, sanitizers are not the only way we can detect UB -- we also have Miri, and now these checks. It would probably be confusing to people familiar with sanitizers if these kinds of debug assertions were mixed up with ubsan/msan and friends.

# Mentors or Reviewers

Myself, and possibly @saethlin ?

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by RalfJung** [comment]
This has been seconded more than 10 days ago, does that mean it got accepted?

**Comment by Nilstrieb** [comment]
the mark-as-accepted process is still manual, but seems ok
