### ISSUE TITLE
convert this repository to use github pages

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#73]
The current repository is just a bunch of mark down files in a directory. This is very hip and low-tech, but it'd be nice if we could have automatically rendered content. A partial list follows:

- the working group table on the front page
- the working group check-in 
- a blog and an announcement page
- the expert map could be rendered from a machine-readable TOML file

If we ported over to a jekyll setup and publishing via github pages, that would be awesome.

**Comment by nikomatsakis** [comment]
I'm marking this as help-wanted -- it'd be great to find someone who wants to spearhead this. If you think that might be you, please drop a line on the **#t-compiler/wg-meta** stream of [the rust-lang zulip](https://github.com/rust-lang/compiler-team/blob/master/about/chat-platform.md).

**Comment by unbalancedparentheses** [comment]
I started working on this and @igaray is helping me. I should have something by Monday. I could not find the working group check-in yet. By working group check-in @nikomatsakis you mean the calendar of when each working group meets?

**Comment by wesleywiser** [comment]
The current working group check-in schedule is at https://github.com/rust-lang/compiler-team/blob/master/about/triage-meeting.md but also look at #67 which changes it.

**Comment by unbalancedparentheses** [comment]
I will check it, thanks!

**Comment by nikomatsakis** [comment]
@unbalancedparentheses hey, awesome! I was just going to put some work into advertising, glad you saved me the effort. =)

**Comment by davidtwco** [comment]
@pietroalbini I was wondering if you had any insights into why #118 doesn't seem to work despite having been merged...

**Comment by pietroalbini** [comment]
@davidtwco [rustc needs to be installed](https://travis-ci.com/rust-lang/compiler-team/builds/119909957#L450) for the deploy script to work.

**Comment by davidtwco** [comment]
@pietroalbini sorry, I should have spotted that myself, I didn't see the Travis log from my phone when I had sent that message.

**Comment by davidtwco** [comment]
Looks like it's now available at [this address](https://rust-lang.github.io/compiler-team/) but it's pretty broken, presumably the configuration file needs changed:

https://github.com/rust-lang/compiler-team/blob/9da42d3640711388f7654410d98b54c4a1710fea/config.toml#L1

**Comment by spastorino** [comment]
I'd say that this is already done and `baseURL` was updated. I've opened an issue with some broken links and missing minutes after the merge but I'd just close this.
