### ISSUE TITLE
Website: Procedures has empty landing page

### ISSUE THREAD

**Issue by Ablesius** [rust-lang/compiler-team#732]
Hi!

I noticed that the [Procedures](https://rust-lang.github.io/compiler-team/procedures/) page is just an empty landing page (see screenshot):
 
![screenshot of empty landing page for procedures; it only shows a white background and has some links on the left side bar menu](https://github.com/rust-lang/compiler-team/assets/11044802/91d61de2-5c4b-4b42-a4ca-3174666438ab)

I'm not sure, it looks like maybe the text "Compiler team procedures are documented on the
[Rust forge](https://forge.rust-lang.org/compiler/index.html)" from the side bar ought to be shown on the landing page instead? You'll notice that that is mostly just text, with the exception of "Rust forge", which is a link. That's why I think you maybe intended to have that on the landing page itself, not the side bar menu. I could be wrong though!

Best,
Lexi

**Comment by Nilstrieb** [comment]
cc @apiraino

**Comment by Ablesius** [comment]
https://github.com/rust-lang/compiler-team/pull/733 #733 merged, I'll close this! Feel free to change anything you don't agree with of course :)
