### ISSUE TITLE
Add a `--emit=nameres` for IDEs

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/compiler-team#749]
# Proposal

As discussed in [this Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/187679-t-compiler.2Fwg-parallel-rustc/topic/How.20does.20parallel.20rustc.20do.20name.20resolution.3F) (and several others in `t-compiler/rust-analyzer`), name resolution in rust-analyzer is slow and extremely serial: it gates all IDE functionality until name resolution is completed for the entire dependency graph. While there are several promising avenues for us to improve rust-analyzer's performance without introducing external state, I'm curious how effective reusing `rustc`'s name resolution results—exposed via an additive `--emit=nameres` mode—would be in speeding up rust-analyzer.

I don't expect this to be particularly helpful for Cargo-based users of rust-analyzer (as rust-analyzer largely requires the results of a `cargo metadata` execution...), but my employer's usage of [Buck2](https://buck2.build/) make this a somewhat viable experiment for two reasons:
- Buck2 is pervasively used with remote execution/caching, which means that a `cargo check`-equivalent build is effectively free for most users (I assume a `cargo check` is a strict superset of the work required to produce a `--emit=nameres`). 
- the process to create a [`rust-project.json`](https://rust-analyzer.github.io/manual.html#non-cargo-based-projects) (rust-analyzer's `cargo-metadata` equivalent for non-Cargo build systems) from Buck is  roughly equivalent to running a `cargo check` for build script/procedural macro reasons.

This mode does not need to be stabilized as I can either use a nightly or a `RUSTC_BOOTSTRAP`'d rustc on the stable channel.

# Mentors or Reviewers

@oli-obk 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by apiraino** [comment]
Closing MCP after discussion on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Add.20a.20.60--emit.3Dnameres.60.20for.20IDEs.20compiler-team.23749/near/444474617)
