### ISSUE TITLE
Project Goals Discussion

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/compiler-team#751]
# Meeting proposal info

- **Title:** Project Goals
- **Type:** non-technical
  
# Summary

@nikomatsakis wants to present Project Goals to the team and discuss possible goals for the Compiler Team.

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/content/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/content/about/steering-meeting.md
[proc]: https://forge.rust-lang.org/compiler/steering-meeting/submit.html
[this template]: https://github.com/rust-lang/compiler-team/blob/master/templates/steering-meeting-proposal.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by apiraino** [comment]
@wesleywiser the project goals 2024 were just [announced and published](https://blog.rust-lang.org/2024/08/12/Project-goals.html). I think this meeting does not need to happen anymore?

**Comment by lqd** [comment]
I think this meeting happened, didn’t it?

**Comment by apiraino** [comment]
Ah you're right. We usually try to link references when a meeting happens. Checking now.

- Here's a [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/project.20goals.20meeting.20tomorrow/near/441487785) about project goals
- Here's a [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.22Rust.20for.20linux.22.20project.20goal/near/445247727) about rust-for-linux
