### ISSUE TITLE
Don't track `--emit=` options as part of crate SVH

### ISSUE THREAD

**Issue by chbaker0** [rust-lang/compiler-team#769]
# Proposal

The list of artifact types passed to `--emit=` does not affect the contents of those artifacts (with one exception). If `foo.rlib` depends on `bar.rlib` which was generated with `--emit=link`, then overwritten with e.g. `--emit=link,dep-info`, a downstream rustc invocation should still be able to use the newer `bar.rlib`.

The one exception is with `--emit=metadata,...`: if `metadata` is passed alone the `.rmeta` output does not contain MIR, so it is not suitable for building `.rlib` dependents. However, this results in an obvious compile error like `error: missing optimized MIR for an item in the crate foo`, and cannot cause the incorrectness that the SVH check prevents.

Excluding the `--emit` list from the SVH allows more flexibility when building Rust code in third-party build systems.

# Mentors or Reviewers

TBD

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by cjgillot** [comment]
From the zulip discussion and my own reflexion, this should go ahead provided the questions around `--emit metadata` get answered. 
@rustbot second
