### ISSUE TITLE
Deprecate `-Csoft-float`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/compiler-team#779]
# Proposal

The `-Csoft-float` flag is unsound and cannot really be salvaged. It should be deprecated and turned into a NOP, or removed.

See https://github.com/rust-lang/rust/issues/129893 for context. The summary is: this flag only has any effect on (32-bit) ARM `*eabihf` targets. It is equivalent to GCC/clang `-mfloat-abi=soft`, and as that name makes clear, it changes the ABI. When code built with `-Csoft-float` calls other code built without that flag (such as the standard library), and there are float types passed in that call, we have an ABI mismatch and hence UB. For that reason, we have the `*eabi` targets: they ensure that everything is consistently built with the soft-float ABI. This flag might predate those targets; it was added in https://github.com/rust-lang/rust/pull/9617 before Rust 1.0 and has seen very little discussion since then. The ARM folks that spoke up in https://github.com/rust-lang/rust/issues/129893 all agreed it has no use; in the worst case where someone uses a `*eabihf` target and that flag because there is no corresponding `*eabi` target, we "just" need to add the corresponding target.

# Mentors or Reviewers

It's already implemented at https://github.com/rust-lang/rust/pull/129897, waiting for a review.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by compiler-errors** [comment]
👍 

@rustbot second

**Comment by Urgau** [comment]
It's been a over 10 days, there is a second, many thumbs up and no objections. MCP accepted.

@rustbot label -final-comment-period +major-change-accepted
