### ISSUE TITLE
Remove the `run-pass-valgrind` test suite

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/compiler-team#792]
# Proposal

Remove the `run-pass-valgrind` test suite. This test suite is not properly hooked up to bootstrap, and `run-pass-valgrind` tests don't actually get exercised under valgrind. See <https://github.com/rust-lang/rust/blob/1b3b8e7b0265162853c650ead09905bc3cdaeae9/src/tools/compiletest/src/runtest/valgrind.rs#L7-L12>. Providing valgrind paths was not hooked up to bootstrap and our CI jobs don't run it. `opt-dist` currently run the `run-pass-valgrind` tests but because it's not properly hooked up in bootstrap, they are just naive `run-pass` tests.

# Mentors or Reviewers

Bootstrap reviewers (@Kobzol who is already reviewing the https://github.com/rust-lang/rust/pull/131351 PR).

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by Noratrieb** [comment]
i feel like an MCP is overkill for something like this. tests that don't work and don't run are obviously bad!
(don't wait for the 10 days, just merge)

**Comment by apiraino** [comment]
As I said on Zulip, I agree but I felt that an MCP could be useful to let everyone know

**Comment by apiraino** [comment]
anyway

@rustbot label -final-comment-period +major-change-accepted
