### ISSUE TITLE
Create a notification group for WASM

### ISSUE THREAD

**Issue by juntyr** [rust-lang/compiler-team#794]
# Proposal

A new notification group “wasm” is created for the WASM targets. The group will use the existing O-wasm, O-wasi, and O-emscripten labels. The notification group will provide target-specific expertise when needed (and reduce the amount of pings specifically for @alexcrichton).

The group will also have aliases for “wasi” and “emscripten”.

# Mentors or Reviewers

@jieyouxu 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jieyouxu** [comment]
Discussed with @davidtwco, we didn't think that this needed an MCP, so I'm going to mark this as accepted without the final comment period.

@rustbot second

**Comment by jieyouxu** [comment]
As mentioned above

@rustbot label -final-comment-period +major-change-accepted
