### ISSUE TITLE
Formatting the rust-lang/rust repository

### ISSUE THREAD

**Issue by Centril** [rust-lang/compiler-team#80]
# Meeting proposal info

- **Title:** RFC: Format the `rust-lang/rust` repository
- **Type:** it's complicated
- **Proposed by:** @Centril 
- **Link:** https://github.com/Centril/rfcs/pull/21
- **Scheduled dates for discussion:**
  - Not yet scheduled, we'll add content here when it gets scheduled

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/procedures/steering-meeting.md

**Comment by eddyb** [comment]
@nikomatsakis meta question: should the last two sections of the template be left off?

**Comment by nikomatsakis** [comment]
We [discussed this in our planning meeting today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/planning.20meeting.202019.2E05.2E10/near/165341688) and decided that we do not need to have a meeting for this. We believe there is general agreement to the plan. However, @Mark-Simulacrum wanted to make sure we uncovered anybody who might have a strong objection, therefore I'm doing a poll:

@rfcbot poll Do you generally approve of this plan to format the repository?

**Comment by nikomatsakis** [comment]
I'm going to close this issue -- we didn't feel this needed to be a meeting.

**Comment by cramertj** [comment]
I actually had a minor question in the meantime: how should we handle the formatting of tests which are testing new syntax that is being introduced in the change, but not yet supported by rustfmt?

**Comment by Centril** [comment]
@cramertj We can exclude those directories explicitly in some manner (either by not having `.enforcefmt` in there or by listing paths explicitly).

**Comment by Centril** [comment]
That actually might be a problem when we use unstable features in the compiler itself... I hope rustfmt handles those gracefully.

**Comment by cramertj** [comment]
It does not-- it currently fails to format anything if your code doesn't parse as a valid rust file.

**Comment by Centril** [comment]
@cramertj ah; but does rustfmt handle nightly features at least for some selection of features?

**Comment by cramertj** [comment]
@Centril it handles some things, but obviously if you've just implemented a feature it wouldn't yet support it.

**Comment by Centril** [comment]
@cramertj Makes sense; this might be a problem in some instances -- which I guess we can fix with opt-outs in case of emergency -- on the other hand, this might also push us to be better at introducing things to rustfmt quicker, which might be a welcome outcome.

**Comment by estebank** [comment]
This feels like it would only be a problem when we start using a feature in the compiler itself, not for the tests, and I would argue that having rustfmt support for features that we feel are useful/safe enough for the compiler should be a priority.

**Comment by cramertj** [comment]
Are we not planning to require that tests also be formatted?

**Comment by Centril** [comment]
@cramertj Sure, but we can do opt-outs for specific folders and files for newly introduced features so as to not let development of new features be hindered by lack of initial rustfmt support. It's sort of a catch-22. Rustfmt can't easily add support without the feature implemented and we couldn't test if we didn't opt out without rustfmt support.

**Comment by estebank** [comment]
Please make it a self contained comment annotation to opt out in tests, not a centralized opt out file.

**Comment by varkor** [comment]
I would like to see some discussion about the settings we use for rustfmt in rustc, but I definitely think formatting the repository is a good idea overall.

**Comment by Zoxc** [comment]
I would like a tool which can format a branch based on say the last commit before the repo is formatted, injecting a commit which formats the repo. So the procedure for updating a branch would be:
- rebase to the last commit which is unformatted
- run the tool
- rebase to master, but skip the commit formatting the repo
