### ISSUE TITLE
Maintenance and triage

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#90]
# Meeting proposal info

- **Title:** Maintenance and triage
- **Type:** non-technical
- **Proposed by:** @nikomatsakis
- **Link:** https://hackmd.io/dvgegmdgQVSMbC4rcjG6EA?view
- **Scheduled dates for discussion:**
  - ~~2019-05-31~~ -- pending creating more of a plan (no such plan was created)
  - 2019-06-28

# About this issue

This issue corresponds to a meeting proposal for the compiler team
[steering meeting][]. It corresponds to a possible topic of
discussion. You can read more about the [steering meeting procedure
here][proc].

# Comment policy

These issues are meant to be used as an "announcements channel"
regarding the proposal, and not as a place to discuss the technical
details. Feel free to subscribe to updates. We'll post comments when
reviewing the proposal in meetings or making a scheduling decision.
In the meantime, if you have questions or ideas, ping the proposers
on [Zulip] (or elsewhere).

[Zulip]: https://github.com/rust-lang/compiler-team/blob/master/about/chat-platform.md
[steering meeting]: https://github.com/rust-lang/compiler-team/blob/master/about/steering-meeting.md
[proc]: https://github.com/rust-lang/compiler-team/blob/master/procedures/steering-meeting.md
[this template]: https://github.com/rust-lang/compiler-team/blob/master/proposals/_template.md
[hackmd]: https://hackmd.io/
[gist]: https://gist.github.com/

**Comment by nikomatsakis** [comment]
We tentatively decided today to schedule this for May 31, but we'd like to elaborate on the plan some more first. To that end, I've created a [Zulip topic in #t-compiler/wg-meta](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta/topic/maintenance.20and.20triage.20plan) to discuss.

**Comment by nikomatsakis** [comment]
@pnkfelix and I never managed to pull together more details on a plan, and @pnkfelix can't attend at the scheduled time, so we decided to postpone.

**Comment by nikomatsakis** [comment]
We scheduled for discussion June 28

**Comment by pnkfelix** [comment]
(... and then the meeting got pre-empted by a last-minute discussion of whether to backport rust-lang/rust#61207)

**Comment by pnkfelix** [comment]
I'm going to close this. Its come up a couple times in the planning meeting, but I think we basically need to have a more concrete plan of action up front. (Trying to use the design meeting timeslot for a brainstorming session does not seem like it has worked in the past.)

**Comment by pnkfelix** [comment]
(to be clear, I'm closing it with the intent of make a new proposal and opening it once that is drafted...)
